#!/usr/bin/env python3
"""Enrich and expand the Sacred Art Dossiers catalog to 100+ masterworks.

Sprint C.3: Museum API 4K Sacred Art Ingestion Pipeline.
Enriches catalog from 65 to 110 artworks with complete bilingual metadata.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "Anno/Resources/ArtDossiers/art_dossiers_catalog.json"

NEW_ARTWORKS = [
    {
        "artwork_id": "art-prodigal-son-rembrandt",
        "feast_association": "Twenty-Fourth Sunday in Ordinary Time (Parable of the Prodigal Son / Divine Mercy)",
        "title": "The Return of the Prodigal Son",
        "artist": "Rembrandt van Rijn",
        "year_created": "c. 1668",
        "medium": "Oil on canvas",
        "dimensions": "262 cm × 205 cm",
        "current_location": "Hermitage Museum, Saint Petersburg, Russia",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/9/93/Rembrandt_Harmensz_van_Rijn_-_Return_of_the_Prodigal_Son_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Rembrandt_Harmensz_van_Rijn_-_Return_of_the_Prodigal_Son_-_Google_Art_Project.jpg/960px-Rembrandt_Harmensz_van_Rijn_-_Return_of_the_Prodigal_Son_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Rembrandt captures the unfathomable depth of divine mercy in the father's embrace. One of the father's hands is masculine and firm, representing divine strength and justice, while the other is soft and maternal, embodying divine tenderness and boundless compassion.",
        "theological_significance_vi": "Rembrandt khắc họa chiều sâu khôn dò của lòng thương xót Chúa qua vòng tay đón nhận của người cha. Một bàn tay gân guốc biểu trưng cho sức mạnh và sự công chính, bàn tay kia mềm mại từ mẫu biểu trưng cho sự dịu dàng và lòng trắc ẩn bao la của Thiên Chúa."
    },
    {
        "artwork_id": "art-storm-galilee-rembrandt",
        "feast_association": "Twelfth Sunday in Ordinary Time (Calming of the Sea)",
        "title": "The Storm on the Sea of Galilee",
        "artist": "Rembrandt van Rijn",
        "year_created": "1633",
        "medium": "Oil on canvas",
        "dimensions": "160 cm × 128 cm",
        "current_location": "Formerly Isabella Stewart Gardner Museum, Boston, USA",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg/960px-Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Depicting the tempestuous boat where the disciples cry out in terror, Rembrandt highlights the drama of human vulnerability against nature, contrasting human fear with the absolute peace of Christ who commands the winds and waves.",
        "theological_significance_vi": "Khắc họa con thuyền chao đảo giữa cơn cuồng phong dữ dội khi các môn đệ hoảng loạn kêu cứu, Rembrandt làm nổi bật sự mỏng giòn của con người trước nghịch cảnh, đối lập nỗi sợ hãi trần thế với sự bình an tuyệt đối của Đức Kitô Đấng truyền lệnh cho sóng yên biển lặng."
    },
    {
        "artwork_id": "art-presentation-simeon-rembrandt",
        "feast_association": "Feast of the Presentation of the Lord (Candlemas, February 2)",
        "title": "Simeon's Song of Praise (Presentation in the Temple)",
        "artist": "Rembrandt van Rijn",
        "year_created": "1631",
        "medium": "Oil on panel",
        "dimensions": "60.9 cm × 47.9 cm",
        "current_location": "Mauritshuis, The Hague, Netherlands",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/3/39/Rembrandt_Harmensz._van_Rijn_042.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Rembrandt_Harmensz._van_Rijn_042.jpg/960px-Rembrandt_Harmensz._van_Rijn_042.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "An ethereal celestial shaft of light pierces the cavernous Temple of Jerusalem, illuminating the aged Simeon as he holds the Infant Christ and sings the Nunc Dimittis, recognizing the long-awaited Salvation and Light of the Nations.",
        "theological_significance_vi": "Một luồng sáng thiên thượng chiếu rọi không gian uy nghiêm của Đền Thờ Giêrusalem, soi sáng cụ già Simêon đang bồng ẵm Hài Nhi Giêsu và hát vang bài ca Nunc Dimittis, nhận ra Ơn Cứu Độ và Ánh Sáng muôn dân hằng mong đợi."
    },
    {
        "artwork_id": "art-supper-emmaus-rembrandt",
        "feast_association": "Easter Monday / Third Sunday of Easter",
        "title": "The Supper at Emmaus",
        "artist": "Rembrandt van Rijn",
        "year_created": "1648",
        "medium": "Oil on wood",
        "dimensions": "68 cm × 65 cm",
        "current_location": "Musée du Louvre, Paris, France",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/8/87/Rembrandt_Harmensz._van_Rijn_030.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Rembrandt_Harmensz._van_Rijn_030.jpg/960px-Rembrandt_Harmensz._van_Rijn_030.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "In this intimate and reverent setting, the Risen Christ breaks bread, radiating a gentle golden aura as the eyes of the two disciples are opened to recognize their Lord through the Eucharistic action before He vanishes from their sight.",
        "theological_significance_vi": "Trong khung cảnh tĩnh lặng và thánh thiêng, Đấng Phục Sinh bẻ bánh, tỏa ra vầng hào quang êm dịu khi mắt hai môn đệ mở ra để nhận biết Chúa qua cử hành Thánh Thể trước khi Người biến mất khỏi mắt họ."
    },
    {
        "artwork_id": "art-descent-cross-rembrandt",
        "feast_association": "Good Friday of the Passion of the Lord",
        "title": "The Descent from the Cross",
        "artist": "Rembrandt van Rijn",
        "year_created": "1634",
        "medium": "Oil on canvas",
        "dimensions": "158 cm × 117 cm",
        "current_location": "Hermitage Museum, Saint Petersburg, Russia",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Rembrandt_-_The_Descent_from_the_Cross_%281634%29.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Rembrandt_-_The_Descent_from_the_Cross_%281634%29.jpg/960px-Rembrandt_-_The_Descent_from_the_Cross_%281634%29.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Through dramatic chiaroscuro, Rembrandt concentrates radiant white light on the lifeless body of the Crucified Lord as Nicodemus, Joseph of Arimathea, and the sorrowful disciples gently lower Him into the shroud.",
        "theological_significance_vi": "Bằng nghệ thuật tương phản sáng tối xuất thần, Rembrandt tập trung nguồn sáng trắng thuần khiết vào thân xác bất động của Đấng Chịu Đóng Đinh khi ông Nicôđêmô, Giuse thành Arimathê cùng các môn đệ đau buồn hạ xác Người xuống khăn liệm."
    },
    {
        "artwork_id": "art-adoration-trinity-durer",
        "feast_association": "Solemnity of the Most Holy Trinity",
        "title": "Adoration of the Trinity (Landauer Altarpiece)",
        "artist": "Albrecht Dürer",
        "year_created": "1511",
        "medium": "Oil on lime wood panel",
        "dimensions": "135 cm × 123.4 cm",
        "current_location": "Kunsthistorisches Museum, Vienna, Austria",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Albrecht_D%C3%BCrer_-_Landauer_Altar_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Albrecht_D%C3%BCrer_-_Landauer_Altar_-_Google_Art_Project.jpg/960px-Albrecht_D%C3%BCrer_-_Landauer_Altar_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Dürer visualizes the entire Communion of Saints—popes, emperors, virgins, and martyrs—floating in adoration beneath God the Father supporting the Crucified Son, overshadowed by the Holy Spirit in the form of a radiant dove.",
        "theological_significance_vi": "Dürer diễn tả toàn thể Hiệp Thông Các Thánh—từ các giáo hoàng, hoàng đế đến các trinh nữ và chứng nhân tử đạo—lơ lửng trong niềm thờ lạy dưới chân Chúa Cha đang nâng đỡ Chúa Con chịu đóng đinh, cùng Chúa Thánh Thần hiện diện trong hình chim bồ câu rực rỡ."
    },
    {
        "artwork_id": "art-adoration-magi-durer",
        "feast_association": "Solemnity of the Epiphany of the Lord (January 6)",
        "title": "Adoration of the Magi",
        "artist": "Albrecht Dürer",
        "year_created": "1504",
        "medium": "Oil on wood",
        "dimensions": "99 cm × 113.5 cm",
        "current_location": "Gallerie degli Uffizi, Florence, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Albrecht_D%C3%BCrer_-_Adoration_of_the_Magi_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Albrecht_D%C3%BCrer_-_Adoration_of_the_Magi_-_Google_Art_Project.jpg/960px-Albrecht_D%C3%BCrer_-_Adoration_of_the_Magi_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Set among classical ruined arches symbolizing the fading Old Covenant, the Three Wise Men present gold, frankincense, and myrrh to the Christ Child, signifying His kingship, divinity, and redemptive sacrifice.",
        "theological_significance_vi": "Đặt trong khung cảnh tàn tích kiến trúc cổ tượng trưng cho Giao Ước Cũ nhường chỗ cho Giao Ước Mới, Ba Vua dâng tiến Hài Nhi vàng, nhũ hương và mộc dược, tôn vinh vương quyền, thiên tính và sứ mạng hy tế cứu chuộc của Người."
    },
    {
        "artwork_id": "art-feast-rosary-durer",
        "feast_association": "Memorial of Our Lady of the Rosary (October 7)",
        "title": "Feast of the Rosary (Rose-Garland Altarpiece)",
        "artist": "Albrecht Dürer",
        "year_created": "1506",
        "medium": "Oil on poplar panel",
        "dimensions": "162 cm × 194.5 cm",
        "current_location": "National Gallery Prague, Prague, Czech Republic",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Albrecht_D%C3%BCrer_-_The_Feast_of_the_Rose_Garlands_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Albrecht_D%C3%BCrer_-_The_Feast_of_the_Rose_Garlands_-_Google_Art_Project.jpg/960px-Albrecht_D%C3%BCrer_-_The_Feast_of_the_Rose_Garlands_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "The Virgin Mary and the Infant Jesus crown Pope Julius II and Emperor Maximilian I with garlands of fresh roses, distributing the Holy Rosary as a spiritual weapon and instrument of universal peace.",
        "theological_significance_vi": "Đức Trinh Nữ Maria và Hài Nhi Giêsu đội triều thiên hoa hồng cho Giáo hoàng Julius II và Hoàng đế Maximilian I, trao ban tràng chuỗi Mân Côi như khí cụ thiêng liêng và biểu tượng của sự hiệp nhất, bình an."
    },
    {
        "artwork_id": "art-four-apostles-durer",
        "feast_association": "Solemnity of Saints Peter and Paul, Apostles (June 29)",
        "title": "The Four Apostles (Saint John, Saint Peter, Saint Mark, Saint Paul)",
        "artist": "Albrecht Dürer",
        "year_created": "1526",
        "medium": "Oil on lindenwood panel",
        "dimensions": "215 cm × 76 cm each",
        "current_location": "Alte Pinakothek, Munich, Germany",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/0/07/Albrecht_D%C3%BCrer_-_Four_Apostles_%28left_panel%29_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Albrecht_D%C3%BCrer_-_Four_Apostles_%28left_panel%29_-_Google_Art_Project.jpg/960px-Albrecht_D%C3%BCrer_-_Four_Apostles_%28left_panel%29_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Monumental in scale and psychological gravity, Dürer pairs John with Peter and Mark with Paul, reflecting the unshakeable foundation of the Apostolic teaching and steadfast adherence to the Word of God.",
        "theological_significance_vi": "Với tầm vóc hoành tráng và chiều sâu nội tâm sâu sắc, Dürer kết hợp Gioan với Phêrô và Máccô với Phaolô, thể hiện nền tảng vững bền của giáo huấn Tông Truyền và lòng trung tín tuyệt đối với Lời Thiên Chúa."
    },
    {
        "artwork_id": "art-st-jerome-study-durer",
        "feast_association": "Memorial of Saint Jerome, Priest and Doctor of the Church (September 30)",
        "title": "Saint Jerome in His Study",
        "artist": "Albrecht Dürer",
        "year_created": "1514",
        "medium": "Master engraving on paper",
        "dimensions": "24.7 cm × 18.8 cm",
        "current_location": "Metropolitan Museum of Art, New York, USA",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/1/18/Albrecht_D%C3%BCrer_-_Saint_Jerome_in_His_Study.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Albrecht_D%C3%BCrer_-_Saint_Jerome_in_His_Study.jpg/960px-Albrecht_D%C3%BCrer_-_Saint_Jerome_in_His_Study.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "A triumph of Renaissance perspective and Christian humanism, the engraving shows Saint Jerome serenely translating sacred scripture into Latin (the Vulgate), guarded by a peaceful lion and dog in celestial sunlight.",
        "theological_significance_vi": "Kiệt tác khắc đồng đỉnh cao của thời Phục Hưng thể hiện Thánh Giêrônimô đang bình an dịch thuật Thánh Kinh sang tiếng Latinh (Bản Phổ Thông Vulgata), bên cạnh sư tử hiền từ và chú chó nằm nghỉ dưới ánh nắng chan hòa."
    },
    {
        "artwork_id": "art-seven-works-mercy-caravaggio",
        "feast_association": "Solemnity of Our Lord Jesus Christ, King of the Universe (Works of Mercy)",
        "title": "The Seven Works of Mercy",
        "artist": "Caravaggio",
        "year_created": "1607",
        "medium": "Oil on canvas",
        "dimensions": "390 cm × 260 cm",
        "current_location": "Pio Monte della Misericordia, Naples, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Sette_opere_di_Misericordia_-_Caravaggio.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Sette_opere_di_Misericordia_-_Caravaggio.jpg/960px-Sette_opere_di_Misericordia_-_Caravaggio.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Caravaggio synthesizes all seven corporeal works of mercy into a single gritty Neapolitan street scene overlooked by the Virgin and Child, emphasizing that true Christian charity is lived amidst raw human poverty.",
        "theological_significance_vi": "Caravaggio tổng hợp cả bảy mối thương xác thành một khung cảnh sống động trên góc phố Napoli dưới ánh nhìn che chở của Đức Mẹ và Hài Nhi, khẳng định rằng đức bác ái Kitô giáo đích thực được thực thi giữa cuộc sống cơ hàn."
    },
    {
        "artwork_id": "art-st-jerome-writing-caravaggio",
        "feast_association": "Memorial of Saint Jerome, Priest and Doctor of the Church (September 30)",
        "title": "Saint Jerome Writing",
        "artist": "Caravaggio",
        "year_created": "1605–1606",
        "medium": "Oil on canvas",
        "dimensions": "112 cm × 157 cm",
        "current_location": "Galleria Borghese, Rome, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/d/da/Caravaggio_-_Saint_Jerome_Writing.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Caravaggio_-_Saint_Jerome_Writing.jpg/960px-Caravaggio_-_Saint_Jerome_Writing.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Saint Jerome is depicted with dramatic intensity, his outstretched quill balancing a contemplative skull on his desk, embodying the monastic balance between scholarly labor, asceticism, and meditation on mortality.",
        "theological_significance_vi": "Thánh Giêrônimô được khắc họa với chiều sâu nội tâm mãnh liệt, ngòi bút lông vươn dài đối xứng với hộp sọ suy niệm trên bàn, biểu trưng cho sự hòa quyện giữa nghiên cứu Kinh Thánh, đời sống khổ tu và sự chiêm ngắm lẽ vô thường."
    },
    {
        "artwork_id": "art-beheading-john-baptist-caravaggio",
        "feast_association": "Memorial of the Passion of Saint John the Baptist (August 29)",
        "title": "The Beheading of Saint John the Baptist",
        "artist": "Caravaggio",
        "year_created": "1608",
        "medium": "Oil on canvas",
        "dimensions": "361 cm × 520 cm",
        "current_location": "Saint John's Co-Cathedral, Valletta, Malta",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/2/23/The_Beheading_of_Saint_John_the_Baptist%2C_by_Caravaggio.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Beheading_of_Saint_John_the_Baptist%2C_by_Caravaggio.jpg/960px-The_Beheading_of_Saint_John_the_Baptist%2C_by_Caravaggio.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "The only artwork Caravaggio ever signed, written in the martyr's pool of blood, depicting the raw brutality of John the Baptist's execution and his unyielding prophetic testimony to the truth of God.",
        "theological_significance_vi": "Tác phẩm duy nhất mang chữ ký của Caravaggio được viết từ chính dòng máu tử đạo, thể hiện sự hy sinh kiên cường của Thánh Gioan Tẩy Giả làm chứng cho chân lý Phúc Âm trước bạo quyền thế gian."
    },
    {
        "artwork_id": "art-inspiration-matthew-caravaggio",
        "feast_association": "Feast of Saint Matthew, Apostle and Evangelist (September 21)",
        "title": "The Inspiration of Saint Matthew",
        "artist": "Caravaggio",
        "year_created": "1602",
        "medium": "Oil on canvas",
        "dimensions": "292 cm × 186 cm",
        "current_location": "Contarelli Chapel, San Luigi dei Francesi, Rome, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/e/eb/The_Inspiration_of_Saint_Matthew_by_Caravaggio.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/The_Inspiration_of_Saint_Matthew_by_Caravaggio.jpg/960px-The_Inspiration_of_Saint_Matthew_by_Caravaggio.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "An angel descends with billowing white drapery to guide the apostle's hand in writing the first Gospel, symbolizing the mystery of divine inspiration illuminating human intellect and obedience.",
        "theological_significance_vi": "Thiên sứ từ trời hạ xuống với tà áo trắng bay lượn để dẫn dắt bàn tay vị Tông đồ chắp bút viết sách Tin Mừng tiên khởi, tượng trưng cho mầu nhiệm ơn linh hứng của Chúa soi sáng tâm trí và sự vâng phục của con người."
    },
    {
        "artwork_id": "art-flight-egypt-caravaggio",
        "feast_association": "Feast of the Holy Innocents, Martyrs (December 28)",
        "title": "The Rest on the Flight into Egypt",
        "artist": "Caravaggio",
        "year_created": "c. 1597",
        "medium": "Oil on canvas",
        "dimensions": "133.5 cm × 166.5 cm",
        "current_location": "Doria Pamphilj Gallery, Rome, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Rest_on_Flight_into_Egypt-Caravaggio_%281597%29.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Rest_on_Flight_into_Egypt-Caravaggio_%281597%29.jpg/960px-Rest_on_Flight_into_Egypt-Caravaggio_%281597%29.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "In a pastoral landscape of gentle stillness, an angelic violinist plays a heavenly lullaby for the sleeping Infant Christ and Mary, while Saint Joseph reverently holds the musical manuscript open for the celestial messenger.",
        "theological_significance_vi": "Trong khung cảnh thiên nhiên thanh bình tĩnh lặng, thiên thần kéo vĩ cầm tấu lên khúc ru thiên quốc cho Hài Nhi Giêsu và Mẹ Maria đang say giấc, trong khi Thánh Giuse cung kính cầm bản nhạc cho sứ thần."
    },
    {
        "artwork_id": "art-alba-madonna-raphael",
        "feast_association": "Solemnity of Mary, Most Holy Mother of God (January 1)",
        "title": "The Alba Madonna",
        "artist": "Raphael",
        "year_created": "c. 1510",
        "medium": "Oil on wood transferred to canvas",
        "dimensions": "94.5 cm diameter",
        "current_location": "National Gallery of Art, Washington, D.C., USA",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Raphael_-_The_Alba_Madonna_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Raphael_-_The_Alba_Madonna_-_Google_Art_Project.jpg/960px-Raphael_-_The_Alba_Madonna_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Composed in a harmonious circular tondo, the Virgin Mary tenderly watches the young Christ and John the Baptist play with a miniature wooden cross, foreshadowing the Passion with tranquil maternal acceptance.",
        "theological_significance_vi": "Được sáng tác trong bố cục hình tròn hoàn hảo, Đức Mẹ dịu dàng nhìn ngắm Chúa Hài Nhi và Gioan Tẩy Giả đang nâng niu cây thánh giá nhỏ, báo trước cuộc Khổ Nạn với sự ưng thuận dịu hiền của tình mẫu tử."
    },
    {
        "artwork_id": "art-ecstasy-cecilia-raphael",
        "feast_association": "Memorial of Saint Cecilia, Virgin and Martyr (November 22)",
        "title": "The Ecstasy of Saint Cecilia",
        "artist": "Raphael",
        "year_created": "c. 1516–1517",
        "medium": "Oil on panel transferred to canvas",
        "dimensions": "220 cm × 136 cm",
        "current_location": "Pinacoteca Nazionale di Bologna, Bologna, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/7/7b/The_Ecstasy_of_St._Cecilia_-_Raphael.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/The_Ecstasy_of_St._Cecilia_-_Raphael.jpg/960px-The_Ecstasy_of_St._Cecilia_-_Raphael.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Cecilia lets earthly musical instruments slip and break at her feet as her soul is elevated to hear the sublime harmony of heavenly angels singing above, illustrating the triumph of divine love over earthly pleasure.",
        "theological_significance_vi": "Thánh Cecilia buông rơi các nhạc cụ trần thế vỡ tan dưới chân khi tâm hồn ngài được nâng lên lắng nghe dàn hợp xướng thiên thần cất tiếng hát trên trời, minh chứng cho sự vượt thắng của tình yêu thần linh trước hư ảo trần thế."
    },
    {
        "artwork_id": "art-deliverance-peter-raphael",
        "feast_association": "Feast of the Chair of Saint Peter / St. Peter in Chains",
        "title": "The Deliverance of Saint Peter",
        "artist": "Raphael",
        "year_created": "1514",
        "medium": "Fresco",
        "dimensions": "500 cm × 660 cm",
        "current_location": "Apostolic Palace, Vatican City",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/0/07/Raffael_028.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Raffael_028.jpg/960px-Raffael_028.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "A nocturnal masterpiece of multiple light sources, showing an angel of blazing light breaking Saint Peter's chains and leading him out of Herod's dark prison, affirming God's unfailing protection of the Church.",
        "theological_significance_vi": "Kiệt tác đêm huyền ảo với sự phối hợp nhiều nguồn sáng, thể hiện thiên sứ rực rỡ bẻ gãy xiềng xích giải thoát Thánh Phêrô khỏi ngục tối của Hêrôđê, khẳng định sự che chở không ngừng của Thiên Chúa dành cho Hội Thánh."
    },
    {
        "artwork_id": "art-pieta-michelangelo",
        "feast_association": "Memorial of Our Lady of Sorrows (September 15)",
        "title": "The Pietà (St. Peter's)",
        "artist": "Michelangelo Buonarroti",
        "year_created": "1498–1499",
        "medium": "Carrara marble sculpture",
        "dimensions": "174 cm × 195 cm",
        "current_location": "St. Peter's Basilica, Vatican City",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/6/67/Michelangelo%27s_Pieta_5450_cropncleaned.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Michelangelo%27s_Pieta_5450_cropncleaned.jpg/960px-Michelangelo%27s_Pieta_5450_cropncleaned.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Carved from a single monolith of Carrara marble, the youthful Mary cradles the crucified Redeemer across her lap with serene surrender, offering His pure sacrifice back to the Eternal Father with open arms.",
        "theological_significance_vi": "Được tạc từ khối đá cẩm thạch Carrara nguyên khối, Mẹ Maria với nét mặt thanh khiết ôm xác Đấng Cứu Chuộc trong lòng với tâm tình vâng phục thánh ý, dang rộng bàn tay dâng hy tế của Người lên Chúa Cha."
    },
    {
        "artwork_id": "art-fall-man-michelangelo",
        "feast_association": "First Sunday of Lent (Creation and Redemption)",
        "title": "The Fall of Man and the Expulsion from the Garden of Eden",
        "artist": "Michelangelo Buonarroti",
        "year_created": "1509–1510",
        "medium": "Fresco",
        "dimensions": "280 cm × 570 cm",
        "current_location": "Sistine Chapel ceiling, Vatican City",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Michelangelo_Buonarroti_026.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Michelangelo_Buonarroti_026.jpg/960px-Michelangelo_Buonarroti_026.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Divided by the Tree of Knowledge, Michelangelo portrays Adam and Eve succumbing to the serpent's deceit on the left and being cast out by an angel bearing a sword on the right, setting the stage for the need of Christ the New Adam.",
        "theological_significance_vi": "Phân chia bởi Cây Biết Thiện Ác, Michelangelo miêu tả Adam và Eva sa ngã trước cám dỗ của con rắn bên trái và bị thiên thần cầm gươm đuổi khỏi vườn địa đàng bên phải, mở ra niềm khao khát Đức Kitô - Adam Mới."
    },
    {
        "artwork_id": "art-last-judgment-fra-angelico",
        "feast_association": "Solemnity of Our Lord Jesus Christ, King of the Universe",
        "title": "The Last Judgment (Triptych)",
        "artist": "Fra Angelico",
        "year_created": "c. 1425–1430",
        "medium": "Tempera on panel",
        "dimensions": "105 cm × 210 cm",
        "current_location": "Museo Nazionale di San Marco, Florence, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Angelico_giudizio_universale_01.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Angelico_giudizio_universale_01.jpg/960px-Angelico_giudizio_universale_01.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Christ sits enthroned among heavenly hosts while the open graves down the center divide the blessed dancing into Paradise from the condemned, presenting an eschatological vision steeped in Dominican theological hope.",
        "theological_significance_vi": "Chúa Kitô ngự trên ngai vinh hiển giữa triều thần thiên quốc, những ngôi mộ mở toang chia đôi ranh giới giữa những người công chính khiêu vũ tiến vào Thiên Đàng và kẻ bị trầm luân, mang lại thị kiến cánh chung đầy hy vọng."
    },
    {
        "artwork_id": "art-san-marco-altarpiece-fra-angelico",
        "feast_association": "Optional Memorial of Saints Cosmas and Damian, Martyrs (September 26)",
        "title": "San Marco Altarpiece (The Virgin and Child with Saints Cosmas and Damian)",
        "artist": "Fra Angelico",
        "year_created": "c. 1438–1443",
        "medium": "Tempera on wood panel",
        "dimensions": "220 cm × 227 cm",
        "current_location": "Museo Nazionale di San Marco, Florence, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Fra_Angelico_005.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Fra_Angelico_005.jpg/960px-Fra_Angelico_005.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "A pioneering Renaissance Sacra Conversazione where Mary sits enthroned in an open garden surrounded by angels and saints, with holy doctor-martyrs Cosmas and Damian kneeling in prayer for the healing of souls.",
        "theological_significance_vi": "Bức tranh Đàm Đạo Thánh tiêu biểu thời Phục Hưng với Đức Mẹ ngự giữa khu vườn mở cùng các thiên thần và các thánh, hai vị thánh tử đạo thầy thuốc Cosma và Đamianô quỳ cầu nguyện cho sự chữa lành tâm hồn nhân loại."
    },
    {
        "artwork_id": "art-linaioli-tabernacle-fra-angelico",
        "feast_association": "Feast of Saint Mark, Evangelist (April 25)",
        "title": "Linaioli Tabernacle (Saint Mark the Evangelist)",
        "artist": "Fra Angelico",
        "year_created": "1433",
        "medium": "Tempera on wood panel",
        "dimensions": "260 cm × 330 cm",
        "current_location": "Museo Nazionale di San Marco, Florence, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/d/da/Fra_Angelico_-_Linaioli_Tabernacle_-_WGA00472.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Fra_Angelico_-_Linaioli_Tabernacle_-_WGA00472.jpg/960px-Fra_Angelico_-_Linaioli_Tabernacle_-_WGA00472.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Framed in monumental gilded marble and surrounded by twelve musical angels, Saint Mark and the holy apostles stand as towering pillars of Catholic orthodoxy and Gospel proclamation.",
        "theological_significance_vi": "Được đóng khung trong đá cẩm thạch mạ vàng lộng lẫy và bao quanh bởi mười hai thiên thần hòa tấu, Thánh Máccô và các thánh tông đồ sừng sững như những cột trụ vững chắc của đức tin và lời rao giảng Tin Mừng."
    },
    {
        "artwork_id": "art-meeting-golden-gate-giotto",
        "feast_association": "Solemnity of the Immaculate Conception of the Blessed Virgin Mary (December 8)",
        "title": "Meeting at the Golden Gate (Joachim and Anne)",
        "artist": "Giotto di Bondone",
        "year_created": "c. 1304–1306",
        "medium": "Fresco",
        "dimensions": "200 cm × 185 cm",
        "current_location": "Scrovegni Chapel, Padua, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/6/61/Giotto_di_Bondone_-_No._6_Scenes_from_the_Life_of_Joachim_-_6._Meeting_at_the_Golden_Gate_-_WGA09176.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Giotto_di_Bondone_-_No._6_Scenes_from_the_Life_of_Joachim_-_6._Meeting_at_the_Golden_Gate_-_WGA09176.jpg/960px-Giotto_di_Bondone_-_No._6_Scenes_from_the_Life_of_Joachim_-_6._Meeting_at_the_Golden_Gate_-_WGA09176.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Giotto renders the chaste and tender reunion of Saint Joachim and Saint Anne at the Golden Gate of Jerusalem, symbolizing the divine blessing from which the Immaculate Virgin Mary was conceived without stain of original sin.",
        "theological_significance_vi": "Giotto diễn tả cuộc hội ngộ tràn đầy yêu thương và thanh khiết của Thánh Gioakim và Thánh Anna tại Cửa Vàng Giêrusalem, biểu trưng cho phúc lành thần linh qua đó Đức Trinh Nữ Maria được thụ thai vô nhiễm nguyên tội."
    },
    {
        "artwork_id": "art-raising-lazarus-giotto",
        "feast_association": "Fifth Sunday of Lent (Lazarus Saturday)",
        "title": "The Raising of Lazarus",
        "artist": "Giotto di Bondone",
        "year_created": "c. 1304–1306",
        "medium": "Fresco",
        "dimensions": "200 cm × 185 cm",
        "current_location": "Scrovegni Chapel, Padua, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Giotto_-_Scrovegni_-_-25-_-_Resurrection_of_Lazarus.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Giotto_-_Scrovegni_-_-25-_-_Resurrection_of_Lazarus.jpg/960px-Giotto_-_Scrovegni_-_-25-_-_Resurrection_of_Lazarus.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Christ raises His right hand in sovereign command as Lazarus emerges bound in swaddling cloths from the rock tomb, demonstrating Jesus' absolute lordship over life, death, and the universal resurrection to come.",
        "theological_significance_vi": "Đức Kitô giơ tay uy quyền truyền phán khi Ladarô bước ra khỏi mộ đá với khăn liệm còn quấn quanh mình, minh chứng vương quyền tuyệt đối của Chúa trên sự sống, sự chết và báo trước sự phục sinh mai hậu."
    },
    {
        "artwork_id": "art-st-francis-ecstasy-el-greco",
        "feast_association": "Memorial of Saint Francis of Assisi (October 4)",
        "title": "Saint Francis of Assisi in Ecstasy",
        "artist": "El Greco",
        "year_created": "c. 1600–1605",
        "medium": "Oil on canvas",
        "dimensions": "110.5 cm × 84 cm",
        "current_location": "Metropolitan Museum of Art, New York, USA",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Saint_Francis_in_Ecstasy_MET_DP124177.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Saint_Francis_in_Ecstasy_MET_DP124177.jpg/960px-Saint_Francis_in_Ecstasy_MET_DP124177.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Saint Francis receives the sacred stigmata against a turbulent sky, his elongated hands and upturned gaze expressing complete mystical conformity to the Passion and wounded heart of Jesus Christ.",
        "theological_significance_vi": "Thánh Phanxicô đón nhận năm dấu thánh in sâu trên thân xác giữa nền trời cuồn cuộn mây gió, đôi bàn tay thon dài và ánh mắt ngước nhìn diễn tả sự kết hợp thần bí trọn vẹn với cuộc Khổ Nạn của Chúa Kitô."
    },
    {
        "artwork_id": "art-holy-trinity-el-greco",
        "feast_association": "Solemnity of the Most Holy Trinity",
        "title": "The Holy Trinity (La Santísima Trinidad)",
        "artist": "El Greco",
        "year_created": "1577–1579",
        "medium": "Oil on canvas",
        "dimensions": "300 cm × 179 cm",
        "current_location": "Museo del Prado, Madrid, Spain",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/3/30/La_Trinidad%2C_por_El_Greco.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/La_Trinidad%2C_por_El_Greco.jpg/960px-La_Trinidad%2C_por_El_Greco.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Influenced by Michelangelo's monumental forms, El Greco shows God the Father embracing the sacrificed body of Christ in the celestial realm, united in the divine breath of the Holy Spirit amidst weeping angels.",
        "theological_significance_vi": "Chịu ảnh hưởng từ vẻ đẹp hùng tráng của Michelangelo, El Greco khắc họa Thiên Chúa Cha nâng đỡ thân xác hiến tế của Chúa Con giữa thiên quốc, hiệp nhất trong hơi thở thánh thiện của Chúa Thánh Thần giữa các thiên thần lệ rơi."
    },
    {
        "artwork_id": "art-tears-peter-el-greco",
        "feast_association": "Holy Thursday (Night of Repentance)",
        "title": "The Tears of Saint Peter (Las lágrimas de San Pedro)",
        "artist": "El Greco",
        "year_created": "c. 1580–1586",
        "medium": "Oil on canvas",
        "dimensions": "108 cm × 89.6 cm",
        "current_location": "Bowes Museum, Barnard Castle, UK",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/5/5a/The_Tears_of_Saint_Peter_by_El_Greco_%28Bowes_Museum%29.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Tears_of_Saint_Peter_by_El_Greco_%28Bowes_Museum%29.jpg/960px-The_Tears_of_Saint_Peter_by_El_Greco_%28Bowes_Museum%29.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "With tear-filled luminous eyes directed toward heaven and hands clasped in profound remorse, Saint Peter embodies the Sacrament of Penance and the boundless mercy that awaits every contrite heart.",
        "theological_significance_vi": "Với đôi mắt ngấn lệ hướng về thiên quốc và đôi bàn tay siết chặt ăn năn, Thánh Phêrô trở thành hiện thân sống động của Bí Tích Hòa Giải và lòng thương xót vô bờ dành cho mọi tâm hồn khiêm nhường sám hối."
    },
    {
        "artwork_id": "art-columba-altarpiece-van-der-weyden",
        "feast_association": "Solemnity of the Epiphany of the Lord (January 6)",
        "title": "The Columba Altarpiece (Adoration of the Magi)",
        "artist": "Rogier van der Weyden",
        "year_created": "c. 1455",
        "medium": "Oil on oak panel",
        "dimensions": "138 cm × 153 cm",
        "current_location": "Alte Pinakothek, Munich, Germany",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Rogier_van_der_Weyden_-_Columba-Altar_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Rogier_van_der_Weyden_-_Columba-Altar_-_Google_Art_Project.jpg/960px-Rogier_van_der_Weyden_-_Columba-Altar_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Set against an intricate Romanesque ruin with a crucifix prominently displayed on the central pillar, this Flemish triptych unites the mystery of the Nativity and Epiphany with the sacrificial purpose of the Incarnation.",
        "theological_significance_vi": "Đặt trong khung cảnh tàn tích kiến trúc La Mã với cây thánh giá xuất hiện trên cây cột trung tâm, bức tranh tam liên họa Flemish này kết nối mầu nhiệm Giáng Sinh và Hiển Linh với cùng đích hy tế của việc Ngôi Lời Nhập Thể."
    },
    {
        "artwork_id": "art-john-altarpiece-van-der-weyden",
        "feast_association": "Solemnity of the Nativity of Saint John the Baptist (June 24)",
        "title": "Saint John Altarpiece (Life and Martyrdom of the Baptist)",
        "artist": "Rogier van der Weyden",
        "year_created": "c. 1455–1460",
        "medium": "Oil on oak panel",
        "dimensions": "77 cm × 48 cm each panel",
        "current_location": "Gemäldegalerie, Berlin, Germany",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/4/49/Rogier_van_der_Weyden_-_Johannesaltar_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Rogier_van_der_Weyden_-_Johannesaltar_-_Google_Art_Project.jpg/960px-Rogier_van_der_Weyden_-_Johannesaltar_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Through three Gothic architectural portals, Van der Weyden depicts the naming of John the Baptist, the Baptism of Christ in the Jordan, and John's martyrdom, celebrating the Precursor of the Messiah.",
        "theological_significance_vi": "Qua ba vòm cổng kiến trúc Gothic tinh xảo, Van der Weyden tái hiện việc đặt tên cho Gioan Tẩy Giả, phép rửa của Chúa Kitô tại sông Giođan và cuộc tử đạo của ngài, tôn vinh vị Tiền Hô vĩ đại của Đấng Cứu Thế."
    },
    {
        "artwork_id": "art-crucifixion-grunewald",
        "feast_association": "Good Friday of the Passion of the Lord",
        "title": "Isenheim Altarpiece: The Crucifixion",
        "artist": "Matthias Grünewald",
        "year_created": "1512–1516",
        "medium": "Oil on limewood panel",
        "dimensions": "269 cm × 307 cm",
        "current_location": "Unterlinden Museum, Colmar, France",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Mathis_Gothart_Gr%C3%BCnewald_-_Crucifixion_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Mathis_Gothart_Gr%C3%BCnewald_-_Crucifixion_-_Google_Art_Project.jpg/960px-Mathis_Gothart_Gr%C3%BCnewald_-_Crucifixion_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Created for a hospital treating plague and skin diseases, this raw masterpiece portrays Christ covered in torn flesh and thorns, offering sick and suffering souls supreme solidarity with their Redeemer.",
        "theological_significance_vi": "Được vẽ cho bệnh viện chăm sóc các bệnh nhân dịch hạch và đau đớn, kiệt tác này khắc họa thân thể Đức Kitô rách nát vì gai nhọn và đòn roi, mang lại niềm an ủi và sự hiệp thông sâu sắc cho những ai đang mang gánh nặng khổ đau."
    },
    {
        "artwork_id": "art-resurrection-grunewald",
        "feast_association": "Easter Sunday of the Resurrection of the Lord",
        "title": "Isenheim Altarpiece: The Resurrection",
        "artist": "Matthias Grünewald",
        "year_created": "1512–1516",
        "medium": "Oil on limewood panel",
        "dimensions": "269 cm × 143 cm",
        "current_location": "Unterlinden Museum, Colmar, France",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/2/23/Mathis_Gothart_Gr%C3%BCnewald_-_Resurrection_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Mathis_Gothart_Gr%C3%BCnewald_-_Resurrection_-_Google_Art_Project.jpg/960px-Mathis_Gothart_Gr%C3%BCnewald_-_Resurrection_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Exploding into a blazing solar corona of incandescent divine glory, the Risen Christ rises triumphant over the sepulcher and Roman guards, radiating the eternal victory of life over death and transfiguration of the flesh.",
        "theological_significance_vi": "Bùng nổ trong vầng hào quang rực rỡ như mặt trời chói lọi, Chúa Phục Sinh chiến thắng khải hoàn bước ra khỏi mộ đá trước sự kinh khiếp của lính canh La Mã, biểu trưng cho sự sống bất diệt và cuộc biến hình vinh hiển."
    },
    {
        "artwork_id": "art-joseph-carpenter-la-tour",
        "feast_association": "Solemnity of Saint Joseph, Spouse of the Blessed Virgin Mary (March 19)",
        "title": "Joseph the Carpenter (Saint Joseph Charpentier)",
        "artist": "Georges de La Tour",
        "year_created": "c. 1642",
        "medium": "Oil on canvas",
        "dimensions": "137 cm × 102 cm",
        "current_location": "Musée du Louvre, Paris, France",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Georges_de_La_Tour_043.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Georges_de_La_Tour_043.jpg/960px-Georges_de_La_Tour_043.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "The young Jesus holds a single glowing candle that illuminates the weathered brow and hardworking hands of Saint Joseph as he bores wood, prefiguring the timber of the Cross and celebrating the dignity of silent holy labor.",
        "theological_significance_vi": "Chúa Giêsu nhỏ bé cầm ngọn nến lung linh soi sáng vầng trán nhọc nhằn và đôi tay lao động cần mẫn của Thánh Giuse khi ngài đục gỗ, báo trước cây gỗ Thánh Giá và tôn vinh phẩm giá của sự lao động thánh thiện trong âm thầm."
    },
    {
        "artwork_id": "art-adoration-shepherds-la-tour",
        "feast_association": "Solemnity of the Nativity of the Lord (Christmas Dawn, December 25)",
        "title": "The Adoration of the Shepherds",
        "artist": "Georges de La Tour",
        "year_created": "c. 1644",
        "medium": "Oil on canvas",
        "dimensions": "107 cm × 137 cm",
        "current_location": "Musée du Louvre, Paris, France",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/6/63/Georges_de_La_Tour_-_The_Adoration_of_the_Shepherds_-_WGA12353.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Georges_de_La_Tour_-_The_Adoration_of_the_Shepherds_-_WGA12353.jpg/960px-Georges_de_La_Tour_-_The_Adoration_of_the_Shepherds_-_WGA12353.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Surrounded by humble peasants and bathed in the warm light of a single candle sheltered by Saint Joseph, the swaddled newborn Christ is contemplated with awe as the true Light coming into the world.",
        "theological_significance_vi": "Giữa những mục đồng chất phác và được sưởi ấm bởi ánh nến do Thánh Giuse che chở, Hài Nhi Giêsu trong khăn tã được chiêm ngắm trong sự kính sợ và tôn sùng như Ánh Sáng thật chiếu rọi trần gian."
    },
    {
        "artwork_id": "art-st-sebastian-la-tour",
        "feast_association": "Optional Memorial of Saint Sebastian, Martyr (January 20)",
        "title": "Saint Sebastian Tended by Saint Irene",
        "artist": "Georges de La Tour",
        "year_created": "c. 1649",
        "medium": "Oil on canvas",
        "dimensions": "167 cm × 131 cm",
        "current_location": "Gemäldegalerie, Berlin, Germany",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/6/64/Georges_de_La_Tour_-_Saint_S%C3%A9bastien_soign%C3%A9_par_sainte_Ir%C3%A8ne_-_Gem%C3%A4ldegalerie.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Georges_de_La_Tour_-_Saint_S%C3%A9bastien_soign%C3%A9_par_sainte_Ir%C3%A8ne_-_Gem%C3%A4ldegalerie.jpg/960px-Georges_de_La_Tour_-_Saint_S%C3%A9bastien_soign%C3%A9_par_sainte_Ir%C3%A8ne_-_Gem%C3%A4ldegalerie.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Saint Irene and her companions courageously tend to the arrow-pierced body of Saint Sebastian by the nocturnal light of a torch, modeling the heroic corporal works of mercy and care for Christian martyrs.",
        "theological_significance_vi": "Thánh nữ Irene và các bạn hữu dũng cảm cứu chữa thân thể đầy tên bắn của Thánh Sebastianô dưới ánh đuốc soi trong đêm, làm gương mẫu cho những việc bác ái anh hùng và lòng trung thành với các chứng nhân đức tin."
    },
    {
        "artwork_id": "art-elevation-cross-rubens",
        "feast_association": "Feast of the Exaltation of the Holy Cross (September 14)",
        "title": "The Elevation of the Cross",
        "artist": "Peter Paul Rubens",
        "year_created": "1610–1611",
        "medium": "Oil on wood panel triptych",
        "dimensions": "462 cm × 341 cm",
        "current_location": "Cathedral of Our Lady, Antwerp, Belgium",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Peter_Paul_Rubens_-_The_Raising_of_the_Cross_-_WGA20216.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Peter_Paul_Rubens_-_The_Raising_of_the_Cross_-_WGA20216.jpg/960px-Peter_Paul_Rubens_-_The_Raising_of_the_Cross_-_WGA20216.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Muscular Roman soldiers strain to heave the heavy wooden cross into the upright position while Christ looks upward in prayer to the Father, presenting the Catholic Baroque affirmation of the dynamic reality of the Holy Sacrifice.",
        "theological_significance_vi": "Những người lính La Mã vạm vỡ dốc toàn lực nâng cây thập giá nặng nề dựng đứng trong khi Đức Kitô ngước mắt cầu nguyện lên Chúa Cha, thể hiện sức sống Baroque tràn trề và khẳng định tính hiện thực của Hy Tế Thánh Thể."
    },
    {
        "artwork_id": "art-descent-cross-rubens",
        "feast_association": "Good Friday of the Passion of the Lord",
        "title": "The Descent from the Cross (Antwerp Triptych)",
        "artist": "Peter Paul Rubens",
        "year_created": "1612–1614",
        "medium": "Oil on panel",
        "dimensions": "420 cm × 310 cm",
        "current_location": "Cathedral of Our Lady, Antwerp, Belgium",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/5/52/Peter_Paul_Rubens_-_The_Descent_from_the_Cross_-_WGA20227.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Peter_Paul_Rubens_-_The_Descent_from_the_Cross_-_WGA20227.jpg/960px-Peter_Paul_Rubens_-_The_Descent_from_the_Cross_-_WGA20227.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "The pristine white burial shroud forms an elegant diagonal path down which the body of Christ flows into the waiting hands of John the Apostle, Mary Magdalene, and the Mother of Sorrows in profound solemnity.",
        "theological_significance_vi": "Tấm khăn liệm trắng tinh khôi tạo thành một đường chéo trang trọng đưa thân xác Chúa Kitô trôi nhẹ vào đôi tay nâng đỡ của Thánh Gioan, Maria Mađalêna và Đức Mẹ Sầu Bi trong sự thành kính vô biên."
    },
    {
        "artwork_id": "art-immaculate-conception-murillo",
        "feast_association": "Solemnity of the Immaculate Conception of the Blessed Virgin Mary (December 8)",
        "title": "The Immaculate Conception of Los Venerables",
        "artist": "Bartolomé Esteban Murillo",
        "year_created": "c. 1678",
        "medium": "Oil on canvas",
        "dimensions": "274 cm × 190 cm",
        "current_location": "Museo del Prado, Madrid, Spain",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Inmaculada_Concepci%C3%B3n_%28Murillo%2C_1678%29.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Inmaculada_Concepci%C3%B3n_%28Murillo%2C_1678%29.jpg/960px-Inmaculada_Concepci%C3%B3n_%28Murillo%2C_1678%29.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Mary is swept heavenward on a crescent moon surrounded by playful cherubs bearing lilies and roses, wrapped in a pure white tunic and blue mantle as the Woman clothed with the sun and free from all sin.",
        "theological_significance_vi": "Đức Mẹ được nâng lên trời trên vầng trăng khuyết giữa đàn thiên thần nhỏ mang hoa huệ và hoa hồng, khoác áo trắng tinh khôi và áo choàng xanh thẳm như Người Phụ Nữ mặc áo mặt trời, hoàn toàn vô nhiễm tội truyền."
    },
    {
        "artwork_id": "art-good-shepherd-murillo",
        "feast_association": "Fourth Sunday of Easter (Good Shepherd Sunday)",
        "title": "The Good Shepherd (El Buen Pastor)",
        "artist": "Bartolomé Esteban Murillo",
        "year_created": "c. 1660",
        "medium": "Oil on canvas",
        "dimensions": "161 cm × 123 cm",
        "current_location": "Museo del Prado, Madrid, Spain",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/7/70/El_Buen_Pastor%2C_por_Bartolom%C3%A9_Esteban_Murillo.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/El_Buen_Pastor%2C_por_Bartolom%C3%A9_Esteban_Murillo.jpg/960px-El_Buen_Pastor%2C_por_Bartolom%C3%A9_Esteban_Murillo.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "The Child Jesus sits tenderly stroking a lost lamb while holding the shepherd's crook, gazing out with boundless sweetness and reminding believers of His sacrificial promise to lay down His life for His sheep.",
        "theological_significance_vi": "Chúa Giêsu lúc thiếu thời ngồi âu yếm vuốt ve chú chiên lạc tay cầm gậy chăn chiên, ánh mắt dịu hiền nhắc nhở các tín hữu về lời hứa hy sinh mạng sống vì đoàn chiên của Đấng Mục Tử Nhân Lành."
    },
    {
        "artwork_id": "art-virgin-annunciate-messina",
        "feast_association": "Solemnity of the Annunciation of the Lord (March 25)",
        "title": "Virgin Annunciate (Maria dell'Annunziata)",
        "artist": "Antonello da Messina",
        "year_created": "c. 1476",
        "medium": "Oil on panel",
        "dimensions": "45 cm × 34.5 cm",
        "current_location": "Galleria Regionale della Sicilia (Palazzo Abatellis), Palermo, Italy",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Antonello_da_Messina_-_Virgin_Annunciate_-_Galleria_Regionale_della_Sicilia%2C_Palermo.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Antonello_da_Messina_-_Virgin_Annunciate_-_Galleria_Regionale_della_Sicilia%2C_Palermo.jpg/960px-Antonello_da_Messina_-_Virgin_Annunciate_-_Galleria_Regionale_della_Sicilia%2C_Palermo.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Mary turns from her reading desk with a raised hand of modest astonishment and serene assent, acknowledging the unseen Archangel Gabriel and uttering her eternal Fiat to the Incarnation.",
        "theological_significance_vi": "Đức Maria ngoảnh lại từ bàn đọc sách với bàn tay giơ lên vừa ngỡ ngàng kín đáo vừa đón nhận thánh ý, lắng nghe lời Sứ thần Gabriel vô hình và cất lên tiếng Fiat ưng thuận mầu nhiệm Nhập Thể."
    },
    {
        "artwork_id": "art-st-jerome-study-messina",
        "feast_association": "Memorial of Saint Jerome, Priest and Doctor of the Church (September 30)",
        "title": "Saint Jerome in His Study",
        "artist": "Antonello da Messina",
        "year_created": "c. 1475",
        "medium": "Oil on lime wood panel",
        "dimensions": "45.7 cm × 36.2 cm",
        "current_location": "The National Gallery, London, UK",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Antonello_da_Messina_-_Saint_Jerome_in_His_Study_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Antonello_da_Messina_-_Saint_Jerome_in_His_Study_-_Google_Art_Project.jpg/960px-Antonello_da_Messina_-_Saint_Jerome_in_His_Study_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Viewed through a magnificent stone archway, Saint Jerome reads in an elevated wooden study within a Gothic cathedral, surrounded by symbols of virtue, faithful peacocks, and his obedient lion strolling in the corridor.",
        "theological_significance_vi": "Nhìn qua vòm đá chạm khắc tuyệt mỹ, Thánh Giêrônimô ngồi đọc sách trong thư phòng gỗ giữa thánh đường Gothic, bao quanh bởi các biểu tượng nhân đức, chim công và chú sư tử ngoan ngoãn dạo bước bên hành lang."
    },
    {
        "artwork_id": "art-dead-christ-holbein",
        "feast_association": "Holy Saturday (The Lord's Resting in the Tomb)",
        "title": "The Body of the Dead Christ in the Tomb",
        "artist": "Hans Holbein the Younger",
        "year_created": "1520–1522",
        "medium": "Oil and tempera on limewood",
        "dimensions": "30.5 cm × 200 cm",
        "current_location": "Kunstmuseum Basel, Basel, Switzerland",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Hans_Holbein_the_Younger_-_The_Body_of_the_Dead_Christ_in_the_Tomb_-_Google_Art_Project.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Hans_Holbein_the_Younger_-_The_Body_of_the_Dead_Christ_in_the_Tomb_-_Google_Art_Project.jpg/960px-Hans_Holbein_the_Younger_-_The_Body_of_the_Dead_Christ_in_the_Tomb_-_Google_Art_Project.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Unsparing in its anatomical realism, Holbein captures the physical tragedy of Christ's death in the claustrophobic stone sepulcher, challenging the viewer to hold fast to faith before the dawn of Easter.",
        "theological_significance_vi": "Khắc họa chân thực và không khoan nhượng nỗi đau thể xác trong mộ đá ngột ngạt, Holbein thể hiện cái chết bi thương của Chúa Kitô, mời gọi các tín hữu kiên vững giữ trọn niềm tin trước bình minh Phục Sinh."
    },
    {
        "artwork_id": "art-st-serapion-zurbaran",
        "feast_association": "Optional Memorial of Saint Serapion of Algiers, Martyr (November 14)",
        "title": "Saint Serapion",
        "artist": "Francisco de Zurbarán",
        "year_created": "1628",
        "medium": "Oil on canvas",
        "dimensions": "120 cm × 103 cm",
        "current_location": "Wadsworth Atheneum, Hartford, Connecticut, USA",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/3/36/Francisco_de_Zurbar%C3%A1n_044.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Francisco_de_Zurbar%C3%A1n_044.jpg/960px-Francisco_de_Zurbar%C3%A1n_044.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Bound by wrists and hanging exhausted in his white Mercedarian habit, the martyr Serapion surrendered his life to ransom Christian captives, radiating profound spiritual stillness in death.",
        "theological_significance_vi": "Bị trói hai cổ tay và buông xuôi kiệt sức trong bộ tu phục màu trắng Dòng Chuộc Kẻ Khốn Cùng, vị thánh tử đạo Serapion đã hy sinh mạng sống để chuộc lại các tù nhân, tỏa rạng sự bình an thánh thiện trong cái chết vì Chúa."
    },
    {
        "artwork_id": "art-agnus-dei-zurbaran",
        "feast_association": "Solemnity of the Most Holy Body and Blood of Christ (Corpus Christi)",
        "title": "Agnus Dei (The Lamb of God)",
        "artist": "Francisco de Zurbarán",
        "year_created": "1635–1640",
        "medium": "Oil on canvas",
        "dimensions": "37.3 cm × 62 cm",
        "current_location": "Museo del Prado, Madrid, Spain",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Agnus_Dei_%28Zurbar%C3%A1n%29.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Agnus_Dei_%28Zurbar%C3%A1n%29.jpg/960px-Agnus_Dei_%28Zurbar%C3%A1n%29.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "A bound, innocent young ram lies on a dark stone slab, an exquisitely tender and silent contemplation of Isaiah's prophecy and the unblemished Paschal Lamb slain for the sins of the world.",
        "theological_significance_vi": "Chú chiên non ngây thơ bị trói chân nằm yên lặng trên phiến đá đen, gợi nhớ sâu sắc lời ngôn sứ Isaia và hình ảnh Chiên Thiên Chúa tinh tuyền hiến tế để xóa tội trần gian."
    },
    {
        "artwork_id": "art-epiphany-bosch",
        "feast_association": "Solemnity of the Epiphany of the Lord (January 6)",
        "title": "The Epiphany (The Adoration of the Magi Triptych)",
        "artist": "Hieronymus Bosch",
        "year_created": "c. 1494",
        "medium": "Oil on oak panels",
        "dimensions": "138 cm × 138 cm",
        "current_location": "Museo del Prado, Madrid, Spain",
        "image_url_highres": "https://upload.wikimedia.org/wikipedia/commons/8/8d/The_Epiphany_Prado_by_Hieronymus_Bosch.jpg",
        "image_url_thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/The_Epiphany_Prado_by_Hieronymus_Bosch.jpg/960px-The_Epiphany_Prado_by_Hieronymus_Bosch.jpg",
        "license_type": "Public Domain - US / CC0 / Life+70",
        "theological_significance_en": "Bosch embeds rich theological allegories within the adoration scene at Bethlehem, warning of spiritual danger through lurking figures while celebrating the Magi's humble worship before the King of Kings.",
        "theological_significance_vi": "Bosch lồng ghép những ẩn dụ thần học phong phú vào khung cảnh tôn thờ tại Bêlem, nhắc nhở về những cạm bẫy tâm linh trong khi tôn vinh lòng thờ lạy khiêm nhường của Ba Vua trước Vua muôn vua."
    }
]


def main() -> None:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    existing_artworks = catalog.get("artworks", [])
    existing_ids = {a["artwork_id"] for a in existing_artworks}

    added = 0
    for item in NEW_ARTWORKS:
        if item["artwork_id"] not in existing_ids:
            existing_artworks.append(item)
            existing_ids.add(item["artwork_id"])
            added += 1

    catalog["total_artworks"] = len(existing_artworks)
    CATALOG_PATH.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Added {added} new sacred artworks. Catalog total is now {len(existing_artworks)}.")


if __name__ == "__main__":
    main()
