#!/usr/bin/env python3
"""Export Anno mock JSON as a paste-ready Swift fixture file."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/mock/anno_fortnight_2026-07-03_2026-07-16.json"
WEEK = ROOT / "data/mock/anno_week_2026-07-03_2026-07-09.json"
OUTPUT = ROOT / "ios-fixtures/AnnoMockData.swift"


SWIFT_HEADER = """// Generated by tools/export_swift_fixture.py.
// Source: data/mock/anno_fortnight_2026-07-03_2026-07-16.json

import Foundation

struct AnnoFixture: Codable {
    let schemaVersion: String
    let generatedOn: String
    let entries: [AnnoEntry]
}

struct AnnoEntry: Codable, Identifiable {
    let id: String
    let date: String
    let weekday: String
    let mockPriority: String
    let liturgical: LiturgicalInfo
    let calendars: CalendarConversions
    let primary: PrimaryContent
    let place: SacredPlace?
    let artwork: ArtworkCandidate
    let sources: [SourceRef]
    let appHooks: AppHooks
}

struct LiturgicalInfo: Codable {
    let rank: String
    let color: String
    let titleEn: String
    let titleVi: String
}

struct CalendarConversions: Codable {
    let julian: String
    let hebrew: String
    let islamicUmmAlQura: String
    let coptic: String
    let ethiopian: String
}

struct PrimaryContent: Codable {
    let type: String
    let titleEn: String
    let titleVi: String
    let summaryEn: String
    let summaryVi: String
    let confidence: String
    let confidenceNoteEn: String
    let confidenceNoteVi: String
}

struct SacredPlace: Codable {
    let name: String
    let latitude: Double
    let longitude: Double
    let confidence: String
    let sourceUrl: String
}

struct ArtworkCandidate: Codable {
    let title: String
    let maker: String
    let dateLabel: String
    let sourceUrl: String
    let status: String
}

struct SourceRef: Codable, Identifiable {
    var id: String { url }
    let label: String
    let url: String
    let type: String
}

struct AppHooks: Codable {
    let heroLineEn: String
    let heroLineVi: String
    let prayerPromptEn: String
    let prayerPromptVi: String
}

enum AnnoMockData {
"""


def main() -> None:
    fixture = json.loads(SOURCE.read_text())
    week = json.loads(WEEK.read_text())

    # Keep the emitted JSON compact enough to paste into a Swift playground or app target.
    json_payload = json.dumps(
        {
            "schema_version": fixture["schema_version"],
            "generated_on": fixture["generated_on"],
            "entries": fixture["entries"],
        },
        ensure_ascii=False,
        indent=2,
    )
    week_ids = json.dumps(week["entry_ids"], ensure_ascii=False, indent=2)

    swift = (
        SWIFT_HEADER
        + f'    static let weekEntryIDs: [String] = {week_ids}\n\n'
        + '    static let fortnightJSON = #"""\n'
        + json_payload
        + '\n"""#\n\n'
        + """    static func loadFortnight() throws -> AnnoFixture {
        let data = Data(fortnightJSON.utf8)
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(AnnoFixture.self, from: data)
    }

    static func loadWeek() throws -> [AnnoEntry] {
        let fixture = try loadFortnight()
        let byID = Dictionary(uniqueKeysWithValues: fixture.entries.map { ($0.id, $0) })
        return weekEntryIDs.compactMap { byID[$0] }
    }
}
"""
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(swift)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
