#!/usr/bin/env python3
"""
generate_batch_9_10.py
Generates Batch 9 (Iberian & Italian Sacred Highways) & Batch 10 (Northern, Eastern & Apostolic Highways)
"""

import json
import os

BATCH_9 = [
    {
        "route_id": "camino_del_norte",
        "title_en": "Camino del Norte: Northern Coastal Route to Santiago",
        "title_vi": "Con Đường Phía Bắc: Tuyến Hải Hành Điệp Trùng Đến Santiago",
        "region": "Northern Spain (Basque Country, Cantabria, Asturias, Galicia)",
        "duration_days": 35,
        "distance_km": 825.0,
        "difficulty": "challenging",
        "overview_en": "The Camino del Norte is one of the most ancient and breathtaking pilgrimage corridors to Santiago de Compostela, hugging the rugged Cantabrian coastline before turning inland across the mountains of Galicia. Used extensively during the 9th and 10th centuries when southern routes were contested, it links medieval monastic foundations, fishing sanctuaries, and the royal pre-Romanesque shrines of Asturias.",
        "overview_vi": "Camino del Norte là một trong những tuyến đường hành hương cổ kính và hùng vĩ nhất tiến về Santiago de Compostela, uốn lượn men theo bờ biển Cantabria hiểm trở trước khi băng qua các dãy núi xứ Galicia. Được các tín hữu sử dụng từ thế kỷ 9 và 10, con đường kết nối các tu viện Trung Cổ, đền thánh miền duyên hải và các di tích tiền Romanesque của hoàng gia Asturias.",
        "spiritual_theme_en": "The rugged ascent of the soul: contemplating the infinity of God across ocean horizons and finding steadfast perseverance through mountainous trials.",
        "spiritual_theme_vi": "Sự thanh luyện tâm linh qua thử thách: chiêm ngắm sự vô biên của Thiên Chúa trước biển cả bao la và rèn luyện đức kiên trì vượt qua đèo cao dốc thẳm.",
        "waypoints": [
            {
                "waypoint_id": "irun_bridge_santiago",
                "name_en": "Parish Church of Nuestra Señora del Juncal (Irún)",
                "name_vi": "Nhà Thờ Giáo Xứ Đức Mẹ Juncal (Irún)",
                "latitude": 43.3381,
                "longitude": -1.7889,
                "order": 1,
                "historical_summary_en": "The border crossing city of Irún marks the traditional Franco-Spanish commencement of the Camino del Norte at the international bridge of Santiago over the Bidasoa River.",
                "historical_summary_vi": "Thành phố biên giới Irún đánh dấu điểm khởi đầu truyền thống của Camino del Norte nối Pháp và Tây Ban Nha tại cây cầu quốc tế Santiago trên sông Bidasoa.",
                "sacred_relic_en": "12th-century Romanesque Black Virgin of Juncal and pilgrims' blessing altar.",
                "sacred_relic_vi": "Tượng Đức Mẹ Juncal thế kỷ 12 phong cách Romanesque và bàn thờ chúc lành cho khách hành hương.",
                "scripture_reading": "Genesis 12:1-2",
                "suggested_prayer_en": "Lord God, as we cross this border and embark upon this coastal pilgrimage, guide our steps and protect us from all spiritual perils. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, khi chúng con bước qua biên giới khởi đầu hành trình hành hương này, xin dẫn lối và gìn giữ chúng con khỏi mọi hiểm nguy. Amen."
            },
            {
                "waypoint_id": "san_sebastian_basilica_santa_maria",
                "name_en": "Basilica of Santa María del Coro (San Sebastián)",
                "name_vi": "Vương Cung Thánh Đường Đức Mẹ Ban Ơn (San Sebastián)",
                "latitude": 43.3236,
                "longitude": -1.9875,
                "order": 2,
                "historical_summary_en": "San Sebastián welcomed pilgrims with hospices along the Bay of La Concha, offering rest before the steep climb over Mount Igueldo.",
                "historical_summary_vi": "Thành phố San Sebastián đón tiếp khách hành hương với các quán trọ dọc Vịnh La Concha trước khi vượt đèo dốc núi Igueldo.",
                "sacred_relic_en": "Ancient statue of Our Lady of the Choir and relics of Saint Sebastian the Martyr.",
                "sacred_relic_vi": "Tượng Đức Mẹ Cổ Kính và thánh tích Thánh Tử Đạo Sebastianô.",
                "scripture_reading": "Psalm 121:1-3",
                "suggested_prayer_en": "Protect our bodies and spirits, O Lord, as we ascend the coastal cliffs in faith. Amen.",
                "suggested_prayer_vi": "Xin Chúa gìn giữ hồn xác chúng con khi chúng con leo lên những vách đá cheo leo trong đức tin. Amen."
            },
            {
                "waypoint_id": "bilbao_cathedral_santiago",
                "name_en": "Cathedral of Santiago (Bilbao)",
                "name_vi": "Nhà Thờ Chính Tòa Thánh Giacôbê (Bilbao)",
                "latitude": 43.2572,
                "longitude": -2.9239,
                "order": 3,
                "historical_summary_en": "Constructed in the 14th century, this Gothic cathedral has stood for seven centuries as the premier sanctuary of Saint James in Vizcaya.",
                "historical_summary_vi": "Xây dựng vào thế kỷ 14, ngôi nhà thờ chính tòa Gothic này đã là đền thánh lớn nhất kính Thánh Giacôbê tại xứ Basque suốt 7 thế kỷ.",
                "sacred_relic_en": "The Pilgrim's Gate (Puerta del Ángel) and 15th-century High Altar of Saint James.",
                "sacred_relic_vi": "Cổng Thiên Thần dành cho khách hành hương và Bàn thờ Thánh Giacôbê thế kỷ 15.",
                "scripture_reading": "James 1:2-4",
                "suggested_prayer_en": "Saint James, strengthen our hearts with the joy of the Gospel as we walk your sacred path. Amen.",
                "suggested_prayer_vi": "Lạy Thánh Giacôbê, xin củng cố tâm hồn chúng con bằng niềm vui Tin Mừng trên con đường thánh này. Amen."
            },
            {
                "waypoint_id": "santander_cathedral_crypt",
                "name_en": "Cathedral of the Assumption and Crypt of the Holy Martyrs (Santander)",
                "name_vi": "Nhà Thờ Chính Tòa Santander và Hầm Mộ Các Thánh Tử Đạo",
                "latitude": 43.4608,
                "longitude": -3.8078,
                "order": 4,
                "historical_summary_en": "Built atop ancient Roman thermal baths, this double-level cathedral houses the heads of the Roman martyrs Emeterius and Celedonius.",
                "historical_summary_vi": "Xây dựng trên nền nhà tắm cổ La Mã, đại thánh đường hai tầng này lưu giữ sọ thánh của hai vị tử đạo Emeterius và Celedonius.",
                "sacred_relic_en": "The Reliquary Heads of Saint Emeterius and Saint Celedonius (3rd century martyrs).",
                "sacred_relic_vi": "Hộp sọ thánh tích của Thánh Emeterius và Thánh Celedonius (tử đạo thế kỷ thứ 3).",
                "scripture_reading": "Revelation 7:13-14",
                "suggested_prayer_en": "Through the prayers of the Holy Martyrs, make our faith unwavering amid the storms of life. Amen.",
                "suggested_prayer_vi": "Nhờ lời chuyển cầu của Các Thánh Tử Đạo, xin cho đức tin chúng con kiên vững giữa giông tố cuộc đời. Amen."
            },
            {
                "waypoint_id": "oviedo_cathedral_camara_santa",
                "name_en": "Metropolitan Cathedral of San Salvador (Oviedo)",
                "name_vi": "Nhà Thờ Chính Tòa San Salvador (Oviedo)",
                "latitude": 43.3625,
                "longitude": -5.8431,
                "order": 5,
                "historical_summary_en": "The spiritual fulcrum of northern pilgrimages, celebrated in the medieval proverb: 'He who goes to Santiago and not to Salvador visits the servant and forgets the Master.'",
                "historical_summary_vi": "Điểm tựa tâm linh của toàn bộ miền bắc Tây Ban Nha, được nhắc đến qua câu ngạn ngữ: 'Ai đến Santiago mà không ghé Salvador là chỉ viếng kẻ đầy tớ mà quên mất Người Thầy.'",
                "sacred_relic_en": "The Sudarium of Oviedo (Holy Face Cloth of Christ) and the Victory Cross inside the UNESCO Cámara Santa.",
                "sacred_relic_vi": "Khăn Liệm Trùm Mặt Chúa Giêsu (Sudarium) và Cây Thánh Giá Khải Hoàn trong Căn Phòng Thánh.",
                "scripture_reading": "John 20:6-7",
                "suggested_prayer_en": "Lord Jesus Christ, Savior of the World, we bow before the relics of your Holy Passion; cleanse our souls in your mercy. Amen.",
                "suggested_prayer_vi": "Lạy Chúa Giêsu Kitô, Đấng Cứu Độ trần gian, chúng con sấp mình trước thánh tích Cuộc Khổ Nạn của Chúa; xin tẩy sạch tâm hồn chúng con. Amen."
            },
            {
                "waypoint_id": "santiago_de_compostela_tomb",
                "name_en": "Cathedral of Santiago de Compostela",
                "name_vi": "Đại Vương Cung Thánh Đường Santiago de Compostela",
                "latitude": 42.8806,
                "longitude": -8.5446,
                "order": 6,
                "historical_summary_en": "The final triumph of the Northern Way, entering Praza do Obradoiro to embrace the Apostle Saint James and pray at his apostolic crypt.",
                "historical_summary_vi": "Đích đến khải hoàn của Tuyến Phía Bắc, bước vào Quảng trường Obradoiro để ôm tượng Thánh Giacôbê và quỳ lạy trước lăng mộ tông đồ.",
                "sacred_relic_en": "The Crypt of Saint James the Greater and the Portico of Glory.",
                "sacred_relic_vi": "Hầm mộ Thánh Giacôbê Tiền Tông Đồ và Cổng Vòm Vinh Hiển.",
                "scripture_reading": "2 Timothy 4:7-8",
                "suggested_prayer_en": "O Holy Apostle Saint James, we offer you our journey and trials; present our prayers to the Risen Christ. Amen.",
                "suggested_prayer_vi": "Lạy Thánh Giacôbê Tông Đồ, chúng con dâng lên ngài trọn vẹn chặng đường hành hương; xin dâng lời nguyện chúng con lên Chúa Kitô Phục Sinh. Amen."
            }
        ]
    },
    {
        "route_id": "via_de_la_plata",
        "title_en": "Vía de la Plata: The Grand Southern Silver Way",
        "title_vi": "Vía de la Plata: Đại Lộ Bạc Xuyên Miền Nam Tây Ban Nha",
        "region": "Southern and Western Spain (Andalusia, Extremadura, Castile and León, Galicia)",
        "duration_days": 40,
        "distance_km": 1000.0,
        "difficulty": "challenging",
        "overview_en": "The Vía de la Plata is the longest and most austere pilgrim highway in Iberia, following the ancient Roman stone road built under Augustus and Tiberius from Seville (Hispalis) through Mérida (Emerita Augusta), Salamanca, and Astorga to the tomb of Saint James in Compostela.",
        "overview_vi": "Vía de la Plata là đại lộ hành hương dài nhất và thanh tịnh nhất bán đảo Iberia, đi theo con đường lát đá La Mã cổ đại xây dựng dưới thời Hoàng đế Augustus và Tiberius từ Seville qua Mérida, Salamanca, Astorga đến mộ Thánh Giacôbê tại Compostela.",
        "spiritual_theme_en": "The vast interior desert: learning silence, radical simplicity, and unwavering trust in Divine Providence across expansive horizons.",
        "spiritual_theme_vi": "Hành trình sa mạc nội tâm: học đòi sự thinh lặng, đức khó nghèo triệt để và lòng tín thác vào Quan Phòng của Thiên Chúa giữa không gian mênh mông.",
        "waypoints": [
            {
                "waypoint_id": "seville_cathedral_giralda",
                "name_en": "Cathedral of Saint Mary of the See (Seville)",
                "name_vi": "Đại Vương Cung Thánh Đường Seville",
                "latitude": 37.3858,
                "longitude": -5.9931,
                "order": 1,
                "historical_summary_en": "The largest Gothic cathedral in the world, Seville Cathedral marks the grand southern milestone of the Vía de la Plata.",
                "historical_summary_vi": "Ngôi nhà thờ Gothic lớn nhất thế giới, đánh dấu điểm xuất phát rực rỡ phía nam của đại lộ Vía de la Plata.",
                "sacred_relic_en": "Relics of Saint Isidore of Seville and the Royal Chapel of Our Lady of the Kings.",
                "sacred_relic_vi": "Hài cốt Thánh Isidore thành Seville và Nguyện đường Hoàng gia Đức Mẹ Các Vua.",
                "scripture_reading": "Psalm 84:5-7",
                "suggested_prayer_en": "Lord, as we begin this long pilgrimage across the plains of Spain, strengthen our resolve and ignite our love for You. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, khi chúng con khởi hành chặng đường vạn dặm này, xin ban thêm sức mạnh và thắp lên lòng mến Chúa trong tâm hồn chúng con. Amen."
            },
            {
                "waypoint_id": "merida_basilica_santa_eulalia",
                "name_en": "Basilica of Santa Eulalia (Mérida)",
                "name_vi": "Vương Cung Thánh Đường Thánh Nữ Eulalia (Mérida)",
                "latitude": 38.9208,
                "longitude": -6.3417,
                "order": 2,
                "historical_summary_en": "The primary Christian martyr sanctuary of Roman Lusitania, commemorating twelve-year-old virgin martyr Eulalia (martyred 304 AD).",
                "historical_summary_vi": "Đền thánh tử đạo cổ nhất xứ Lusitania La Mã, tôn vinh vị thánh nữ tử đạo 12 tuổi Eulalia (tử đạo năm 304).",
                "sacred_relic_en": "The 4th-century Crypt and Relics of Child-Martyr Saint Eulalia of Mérida.",
                "sacred_relic_vi": "Hầm mộ thế kỷ thứ 4 và Hài cốt Thánh Nữ Tử Đạo Eulalia xứ Mérida.",
                "scripture_reading": "Matthew 18:2-4",
                "suggested_prayer_en": "Saint Eulalia, grant us your heroic purity and bold witness to the Gospel in our modern world. Amen.",
                "suggested_prayer_vi": "Lạy Thánh Nữ Eulalia, xin ban cho chúng con lòng trong sạch và lòng can đảm làm chứng nhân cho Tin Mừng. Amen."
            },
            {
                "waypoint_id": "salamanca_cathedrals",
                "name_en": "New and Old Cathedrals of Salamanca",
                "name_vi": "Quần Thể Nhà Thờ Chính Tòa Cũ và Mới Salamanca",
                "latitude": 40.9608,
                "longitude": -5.6664,
                "order": 3,
                "historical_summary_en": "Salamanca, city of universities and theological mastery, welcomed pilgrims across the Roman bridge over the Tormes river.",
                "historical_summary_vi": "Salamanca, thành phố của các viện đại học thần học lỗi lạc, đón tiếp khách hành hương qua cây cầu đá La Mã cổ trên sông Tormes.",
                "sacred_relic_en": "Relics of Saint John of Sahagún and the 12th-century Romanesque Virgin of the Vega.",
                "sacred_relic_vi": "Hài cốt Thánh Gioan thành Sahagún và Tượng Đức Mẹ Vega thế kỷ 12.",
                "scripture_reading": "Proverbs 3:5-6",
                "suggested_prayer_en": "Fill our intellects with Divine Wisdom, Lord, and order our steps according to your holy commandments. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, xin đổ tràn sự khôn ngoan thánh thiện trên chúng con và dẫn dắt từng bước đi theo thánh ý Chúa. Amen."
            },
            {
                "waypoint_id": "astorga_cathedral_santa_maria",
                "name_en": "Cathedral of Saint Mary of Astorga",
                "name_vi": "Nhà Thờ Chính Tòa Đức Mẹ Astorga",
                "latitude": 42.4578,
                "longitude": -6.0569,
                "order": 4,
                "historical_summary_en": "The historic junction where the Vía de la Plata merges into the Camino Francés, guided by the Episcopal Palace designed by Antoni Gaudí.",
                "historical_summary_vi": "Giao lộ lịch sử nơi đại lộ Vía de la Plata hòa nhập vào đường Camino Francés, nổi bật với Dinh Giám mục do kiến trúc sư Antoni Gaudí thiết kế.",
                "sacred_relic_en": "Relics of Saint Turibius of Astorga and the 16th-century Retablo Mayor by Gaspar Becerra.",
                "sacred_relic_vi": "Hài cốt Thánh Turibius xứ Astorga và Bàn thờ chạm khắc gỗ thế kỷ 16 của Gaspar Becerra.",
                "scripture_reading": "Isaiah 40:29-31",
                "suggested_prayer_en": "Grant endurance to our tired limbs, O Christ, as we enter the mountainous ascent to Galicia. Amen.",
                "suggested_prayer_vi": "Lạy Chúa Kitô, xin ban sức bền bỉ cho đôi chân mệt mỏi của chúng con khi tiến vào vùng núi non Galicia. Amen."
            },
            {
                "waypoint_id": "santiago_compostela_silver_route_end",
                "name_en": "Cathedral of Santiago de Compostela",
                "name_vi": "Đại Vương Cung Thánh Đường Santiago de Compostela",
                "latitude": 42.8806,
                "longitude": -8.5446,
                "order": 5,
                "historical_summary_en": "After 1,000 kilometers of desert and mountains, pilgrims of the Silver Way kneel in tears before the Apostle's resting place.",
                "historical_summary_vi": "Sau một ngàn cây số băng qua sa mạc và đèo cao, các khách hành hương của Con Đường Bạc rơi lệ quỳ gối trước lăng mộ Thánh Tông đồ.",
                "sacred_relic_en": "The Silver Tomb of Saint James the Greater and the Great Censer (Botafumeiro).",
                "sacred_relic_vi": "Lăng mộ bạc của Thánh Giacôbê Tiền Tông Đồ và Bình hương khổng lồ Botafumeiro.",
                "scripture_reading": "Psalm 23:1-6",
                "suggested_prayer_en": "We give you thanks, Almighty Father, for bringing us safely across this thousand-kilometer way into the joy of your house. Amen.",
                "suggested_prayer_vi": "Chúng con tạ ơn Chúa Cha Toàn Năng đã gìn giữ chúng con bình an vượt qua ngàn dặm đường dài để đến được nơi thánh điện nhà Chúa. Amen."
            }
        ]
    },
    {
        "route_id": "camino_ignaciano",
        "title_en": "Camino Ignaciano: The Pilgrim Path of Saint Ignatius of Loyola",
        "title_vi": "Camino Ignaciano: Con Đường Hành Hương Biến Đổi của Thánh Inhaxiô Loyola",
        "region": "Northern and Eastern Spain (Basque Country, Navarre, La Rioja, Aragon, Catalonia)",
        "duration_days": 27,
        "distance_km": 650.0,
        "difficulty": "moderate",
        "overview_en": "The Camino Ignaciano retraces the historic spiritual journey undertaken by Saint Ignatius of Loyola in 1522, departing from his ancestral castle in Azpeitia (Loyola) after his profound conversion from knightly vanity, crossing the Pyrenees foothills, the Ebro valley, and the jagged cliffs of Montserrat, culminating in the cave of Manresa where he composed the Spiritual Exercises.",
        "overview_vi": "Camino Ignaciano tái hiện lại hành trình thiêng liêng lịch sử của Thánh Inhaxiô Loyola năm 1522, rời bỏ lâu đài gia tộc tại Azpeitia sau cuộc hoán cải từ người hiệp sĩ kiêu hãnh, băng qua thung lũng sông Ebro, rặng núi đá Montserrat và kết thúc tại hang đá Manresa nơi ngài viết tập Linh Thao.",
        "spiritual_theme_en": "The inner pilgrimage of conversion: discerning God's will, conquering self-love, and seeking 'God in all things' (*Ad Maiorem Dei Gloriam*).",
        "spiritual_theme_vi": "Cuộc hành hương hoán cải nội tâm: phân định thánh ý Chúa, chiến thắng tính ích kỷ và 'tìm kiếm Chúa trong mọi sự' (*Ad Maiorem Dei Gloriam - Để Tôn Vinh Thiên Chúa Hơn*).",
        "waypoints": [
            {
                "waypoint_id": "loyola_sanctuary_conversion_chapel",
                "name_en": "Sanctuary of Loyola (Holy House and Conversion Chapel)",
                "name_vi": "Đền Thánh Loyola (Nhà Thánh và Nguyện Đường Hoán Cải)",
                "latitude": 43.1744,
                "longitude": -2.2828,
                "order": 1,
                "historical_summary_en": "The birthplace of Saint Ignatius where, recovering from a cannonball wound sustained at Pamplona in 1521, he surrendered his sword to Christ after reading the lives of Christ and the saints.",
                "historical_summary_vi": "Nơi sinh của Thánh Inhaxiô, nơi ngài dưỡng thương sau khi bị đạn đại bác gãy chân tại Pamplona năm 1521 và đã dâng thanh gươm cho Chúa sau khi đọc sách Hạnh Các Thánh.",
                "sacred_relic_en": "The Chapel of Conversion inside the Tower House of Loyola.",
                "sacred_relic_vi": "Nguyện Đường Hoán Cải bên trong Lâu Đài Tháp Cổ Loyola.",
                "scripture_reading": "Philippians 3:7-8",
                "suggested_prayer_en": "Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will. Give me only your love and your grace, for these are enough for me. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, xin nhận lấy trọn vẹn tự do, trí nhớ, trí hiểu và toàn bộ ý muốn của con. Chỉ xin ban cho con tình yêu và ân sủng Chúa, vì bấy nhiêu là đủ cho con. Amen."
            },
            {
                "waypoint_id": "aranzazu_sanctuary",
                "name_en": "Sanctuary of Our Lady of Aránzazu (Oñati)",
                "name_vi": "Đền Thánh Đức Mẹ Aránzazu (Oñati)",
                "latitude": 42.9786,
                "longitude": -2.3986,
                "order": 2,
                "historical_summary_en": "Perched upon rugged limestone peaks, Ignatius kept vigil before this Marian shrine, taking a vow of perpetual chastity before setting out across Spain.",
                "historical_summary_vi": "Nằm trên đỉnh núi đá vôi hiểm trở, Thánh Inhaxiô đã canh thức thâu đêm trước tượng Đức Mẹ và khấn giữ đức khiết tịnh trọn đời.",
                "sacred_relic_en": "The Miraculous 15th-Century Stone Virgin of the Thorn Tree (Aránzazu).",
                "sacred_relic_vi": "Tượng Đá Đức Mẹ Bụi Gai Aránzazu thế kỷ 15.",
                "scripture_reading": "2 Corinthians 12:9",
                "suggested_prayer_en": "Holy Mother of Aránzazu, guard our purity and guide our vocational surrender to your Son. Amen.",
                "suggested_prayer_vi": "Lạy Đức Mẹ Aránzazu, xin gìn giữ tâm hồn chúng con trong trắng và dâng hiến trọn vẹn cho Con Mẹ. Amen."
            },
            {
                "waypoint_id": "zaragoza_pillar_ignatian_way",
                "name_en": "Basilica of Our Lady of the Pillar (Zaragoza)",
                "name_vi": "Đại Vương Cung Thánh Đường Đức Mẹ Trụ Cột (Zaragoza)",
                "latitude": 41.6567,
                "longitude": -0.8783,
                "order": 3,
                "historical_summary_en": "Ignatius paused in Zaragoza to venerate the sacred Jasper Pillar, drawing apostolic fortitude from the traditional shrine of Saint James.",
                "historical_summary_vi": "Thánh Inhaxiô dừng chân tại Zaragoza để cầu nguyện bên Trụ Đá Thánh của Đức Mẹ, kín múc sức mạnh tông đồ cho chặng đường phía trước.",
                "sacred_relic_en": "The Holy Pillar of Our Lady and the Altar of the Apparition.",
                "sacred_relic_vi": "Trụ Đá Thánh của Đức Mẹ và Bàn Thờ Hiện Ra.",
                "scripture_reading": "1 Corinthians 16:13-14",
                "suggested_prayer_en": "Mother of the Pillar, make our hearts firm in the defense and propagation of the Faith. Amen.",
                "suggested_prayer_vi": "Lạy Đức Mẹ Trụ Cột, xin làm cho đức tin chúng con kiên vững để bảo vệ và loan truyền chân lý Chúa. Amen."
            },
            {
                "waypoint_id": "montserrat_abbey_black_virgin",
                "name_en": "Santa Maria de Montserrat Abbey",
                "name_vi": "Đan Viện Biển Đức Đức Mẹ Montserrat",
                "latitude": 41.5931,
                "longitude": 1.8375,
                "order": 4,
                "historical_summary_en": "On the eve of the Annunciation in March 1522, Ignatius spent a nocturnal vigil of arms before the Black Madonna of Montserrat, hanging his sword at her altar and donning a beggar's rough sackcloth.",
                "historical_summary_vi": "Đêm vọng Lễ Truyền Tin năm 1522, Thánh Inhaxiô đã canh thức thâu đêm trước tượng Đức Mẹ Đen Montserrat, trao thanh kiếm trên bàn thờ và mặc áo vải thô của người hành khất.",
                "sacred_relic_en": "The Miraculous 12th-Century Black Virgin of Montserrat (La Moreneta).",
                "sacred_relic_vi": "Tượng Đức Mẹ Đen Montserrat (La Moreneta) thế kỷ 12.",
                "scripture_reading": "Ephesians 6:10-13",
                "suggested_prayer_en": "Queen of Montserrat, we surrender our worldly pride; clothe us in the armor of God and humility of Christ. Amen.",
                "suggested_prayer_vi": "Lạy Nữ Vương Montserrat, chúng con xin cởi bỏ thói kiêu căng; xin mặc cho chúng con áo giáp của Thiên Chúa và đức khiêm nhường của Chúa Kitô. Amen."
            },
            {
                "waypoint_id": "manresa_cave_saint_ignatius",
                "name_en": "The Holy Cave of Saint Ignatius (La Cova de Manresa)",
                "name_vi": "Hang Đá Thánh Inhaxiô (La Cova de Manresa)",
                "latitude": 41.7219,
                "longitude": 1.8286,
                "order": 5,
                "historical_summary_en": "For eleven months in 1522-1523, Ignatius lived as a hermit in this natural rock cave overlooking the Cardener River, experiencing supreme mystical illuminations and writing the immortal *Spiritual Exercises*.",
                "historical_summary_vi": "Suốt 11 tháng năm 1522-1523, Thánh Inhaxiô đã sống ẩn tu trong hang đá này bên bờ sông Cardener, trải qua những thị kiến thần bí cao siêu và hoàn tất tập *Linh Thao* bất hủ.",
                "sacred_relic_en": "The Natural Rock Cave of the Spiritual Exercises and the Cardener Illumination Memorial.",
                "sacred_relic_vi": "Hang Đá Tự Nhiên nơi viết sách Linh Thao và Di Tích Thần Thị Bên Sông Cardener.",
                "scripture_reading": "Romans 8:38-39",
                "suggested_prayer_en": "Teach us, good Lord, to serve You as You deserve: to give and not to count the cost; to fight and not to heed the wounds; to toil and not to seek for rest; to labor and to ask for no reward save that of knowing that we do Your will. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, xin dạy con biết phụng sự Chúa cho xứng đáng: biết cho đi mà không tính toán; biết chiến đấu mà không ngại thương tích; biết làm việc mà không tìm an nhàn; biết hy sinh mà không tìm phần thưởng nào khác ngoài việc biết mình đang thi hành thánh ý Chúa. Amen."
            }
        ]
    },
    {
        "route_id": "via_lauretana",
        "title_en": "Via Lauretana: The Umbrian-Marche Marian Way",
        "title_vi": "Via Lauretana: Tuyến Hành Hương Thánh Mẫu Từ Assisi Đến Loreto",
        "region": "Central Italy (Umbria and Marche)",
        "duration_days": 7,
        "distance_km": 150.0,
        "difficulty": "moderate",
        "overview_en": "The Via Lauretana is the historic Marian pilgrimage highway of Italy, traversing the picturesque Apennine spine from the Franciscan sanctuary of Assisi through Spello, Foligno, and Tolentino to the Holy House of Loreto on the Adriatic coast.",
        "overview_vi": "Via Lauretana là tuyến hành hương Thánh Mẫu lịch sử của nước Ý, băng qua dãy núi Apennine tuyệt đẹp từ đền thánh Phanxicô tại Assisi qua Spello, Tolentino đến Nhà Thánh Nazareth tại Loreto bên bờ biển Adriatic.",
        "spiritual_theme_en": "From the Cross of Assisi to the Home of the Incarnation: walking with Mary from Franciscan humility to the dwelling of the Word made Flesh.",
        "spiritual_theme_vi": "Từ Thánh Giá Assisi đến Ngôi Nhà Nhập Thể: bước đi cùng Đức Mẹ từ tinh thần khó nghèo Phanxicô đến mái ấm của Ngôi Lời Nhập Thể.",
        "waypoints": [
            {
                "waypoint_id": "assisi_basilica_santa_maria_angeli",
                "name_en": "Papal Basilica of Saint Mary of the Angels (Porziuncola, Assisi)",
                "name_vi": "Đại Vương Cung Thánh Đường Đức Mẹ Các Thiên Thần (Porziuncola, Assisi)",
                "latitude": 43.0578,
                "longitude": 12.5806,
                "order": 1,
                "historical_summary_en": "The cradle of the Franciscan Order and the tiny chapel of the Porziuncola where Saint Francis founded the Friars Minor and died in 1226.",
                "historical_summary_vi": "Cái nôi của Dòng Phanxicô và ngôi nguyện đường nhỏ Porziuncola nơi Thánh Phanxicô lập dòng và qua đời năm 1226.",
                "sacred_relic_en": "The 10th-century Chapel of the Porziuncola and the Transito Chapel.",
                "sacred_relic_vi": "Nguyện đường Porziuncola thế kỷ 10 và Nguyện đường Transito nơi Thánh Phanxicô về trời.",
                "scripture_reading": "Luke 1:46-50",
                "suggested_prayer_en": "Holy Queen of the Angels, obtain for us the pardon of all our sins as we set out on this path of prayer. Amen.",
                "suggested_prayer_vi": "Lạy Nữ Vương Các Thiên Thần, xin ban ơn tha thứ mọi tội lỗi cho chúng con khi khởi đầu con đường cầu nguyện này. Amen."
            },
            {
                "waypoint_id": "spello_church_santa_maria_maggiore",
                "name_en": "Church of Santa Maria Maggiore (Spello)",
                "name_vi": "Nhà Thờ Đức Mẹ Cả (Spello)",
                "latitude": 42.9917,
                "longitude": 12.6736,
                "order": 2,
                "historical_summary_en": "Medieval stone town harboring Pinturicchio's sublime Renaissance frescoes of the Annunciation and Nativity in the Baglioni Chapel.",
                "historical_summary_vi": "Ngôi làng đá Trung Cổ lưu giữ kiệt tác bích họa Phục Hưng về Truyền Tin và Giáng Sinh của danh họa Pinturicchio.",
                "sacred_relic_en": "The Baglioni Annunciation Chapel frescoes and 13th-century Romanesque Virgin.",
                "sacred_relic_vi": "Bích họa Truyền Tin Nguyện đường Baglioni và Tượng Đức Mẹ Romanesque thế kỷ 13.",
                "scripture_reading": "Luke 1:30-33",
                "suggested_prayer_en": "May your Word take root in our hearts, Lord, as it was conceived in Mary at the Annunciation. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, xin cho Lời Chúa bén rễ sâu trong tâm hồn chúng con như đã Nhập Thể nơi lòng Đức Mẹ. Amen."
            },
            {
                "waypoint_id": "tolentino_basilica_san_nicola",
                "name_en": "Basilica of Saint Nicholas of Tolentino",
                "name_vi": "Vương Cung Thánh Đường Thánh Nicôla Tolentino",
                "latitude": 43.2089,
                "longitude": 13.2847,
                "order": 3,
                "historical_summary_en": "Sanctuary of the great Augustinian mystic and intercessor for holy souls in Purgatory, Saint Nicholas of Tolentino (1245–1305).",
                "historical_summary_vi": "Đền thánh của vị đại thần bí dòng Augustinô và là đấng bầu cử cho các linh hồn Luyện Ngục, Thánh Nicôla Tolentino.",
                "sacred_relic_en": "The Incorrupt Holy Arms of Saint Nicholas of Tolentino inside the Cappellone.",
                "sacred_relic_vi": "Cánh tay thánh tích không hư nát của Thánh Nicôla Tolentino trong Nhà Nguyện Lớn.",
                "scripture_reading": "2 Maccabees 12:44-46",
                "suggested_prayer_en": "Saint Nicholas of Tolentino, intercede for the Holy Souls in Purgatory and obtain for us peace of heart. Amen.",
                "suggested_prayer_vi": "Lạy Thánh Nicôla Tolentino, xin cầu bầu cho các linh hồn nơi Luyện Ngục và ban bình an cho tâm hồn chúng con. Amen."
            },
            {
                "waypoint_id": "loreto_basilica_santa_casa_end",
                "name_en": "Pontifical Basilica of the Holy House of Loreto",
                "name_vi": "Đại Vương Cung Thánh Đường Nhà Thánh Loreto",
                "latitude": 43.4410,
                "longitude": 13.6105,
                "order": 4,
                "historical_summary_en": "The glorious culmination of the Via Lauretana, entering the Holy House of the Annunciation where the Word became Flesh.",
                "historical_summary_vi": "Đích đến vinh hiển của tuyến Via Lauretana, bước vào Ngôi Nhà Thánh Nazareth nơi Ngôi Lời đã Nhập Thể làm Người.",
                "sacred_relic_en": "The Sacred Walls of the Holy House of Nazareth and the Black Madonna of Loreto.",
                "sacred_relic_vi": "Ba Bức Tường Đá Thánh của Nhà Nazareth và Tượng Đức Mẹ Đen Loreto.",
                "scripture_reading": "John 1:14",
                "suggested_prayer_en": "O Holy House of Loreto, cradle of our Salvation, welcome our prayers and shelter our families in the holy peace of Jesus, Mary, and Joseph. Amen.",
                "suggested_prayer_vi": "Lạy Nhà Thánh Loreto, cái nôi của Ơn Cứu Độ, xin đón nhận kinh nguyện chúng con và che chở gia đình chúng con trong bình an thánh thiện của Chúa Giêsu, Mẹ Maria và Thánh Cả Giuse. Amen."
            }
        ]
    }
]

BATCH_10 = [
    {
        "route_id": "way_of_st_paul",
        "title_en": "The Way of Saint Paul: The Apostolic Highway of the Mediterranean",
        "title_vi": "Con Đường Thánh Phaolô: Đại Lộ Tông Đồ Xuyên Địa Trung Hải",
        "region": "Greece, Turkey, and Italy",
        "duration_days": 21,
        "distance_km": 1800.0,
        "difficulty": "challenging",
        "overview_en": "The Way of Saint Paul traces the momentous missionary journeys and final captivity voyage of the Apostle to the Gentiles across the eastern and central Mediterranean, from his first European landfall in Philippi through Thessaloniki, Athens, Corinth, and Ephesus, culminating in Rome where he was martyred for Christ.",
        "overview_vi": "Con Đường Thánh Phaolô tái hiện các chuyến hành trình truyền giáo vĩ đại và chuyến hải hành tù nhân cuối cùng của Tông Đồ Dân Ngoại qua Địa Trung Hải, từ bước chân đầu tiên trên đất Châu Âu tại Philippi qua Thessaloniki, Athens, Corinth, Ephesus và kết thúc tại Roma nơi ngài chịu tử đạo.",
        "spiritual_theme_en": "Apostolic zeal and the triumph of the Cross: proclaiming Christ crucified to the cultures of the world without compromise or fear.",
        "spiritual_theme_vi": "Lòng nhiệt thành tông đồ và sự khải hoàn của Thập Giá: loan báo Chúa Kitô chịu đóng đinh cho mọi nền văn hóa thế giới mà không sợ hãi hay thỏa hiệp.",
        "waypoints": [
            {
                "waypoint_id": "philippi_baptistery_lydia",
                "name_en": "Ancient Philippi and the Baptistery of Saint Lydia",
                "name_vi": "Di Tích Cổ Philippi và Nơi Rửa Tội Thánh Nữ Lydia",
                "latitude": 41.0131,
                "longitude": 24.2869,
                "order": 1,
                "historical_summary_en": "In AD 49, Paul responded to the 'Macedonian Call' (*Acts 16:9*), baptizing Saint Lydia by the Gangites River as the first recorded Christian convert in Europe.",
                "historical_summary_vi": "Năm 49 sau Công Nguyên, Thánh Phaolô đáp lại 'Tiếng Gọi Macedonia' (*Công vụ 16:9*), rửa tội cho Thánh Nữ Lydia bên dòng sông Gangites—người tòng giáo Kitô đầu tiên tại Châu Âu.",
                "sacred_relic_en": "The Prison of Saint Paul and Silas in Philippi and the Open-Air Stream Baptistery of Lydia.",
                "sacred_relic_vi": "Tù ngục Thánh Phaolô và Silas tại Philippi cùng Báp-têm đài ngoài trời của Thánh Nữ Lydia.",
                "scripture_reading": "Acts 16:13-15",
                "suggested_prayer_en": "Lord Jesus, open our hearts as you opened the heart of Lydia to accept the saving truth of your Gospel. Amen.",
                "suggested_prayer_vi": "Lạy Chúa Giêsu, xin mở lòng chúng con như Chúa đã mở lòng Thánh Nữ Lydia để đón nhận chân lý cứu độ của Tin Mừng. Amen."
            },
            {
                "waypoint_id": "thessaloniki_church_saint_demetrius",
                "name_en": "Basilica of Saint Demetrius and Catacomb of Paul (Thessaloniki)",
                "name_vi": "Vương Cung Thánh Đường Thánh Demetrius (Thessaloniki)",
                "latitude": 40.6386,
                "longitude": 22.9472,
                "order": 2,
                "historical_summary_en": "Paul preached in the synagogue of Thessaloniki for three Sabbaths, planting the vibrant community to whom he addressed the earliest New Testament epistles.",
                "historical_summary_vi": "Thánh Phaolô rao giảng tại hội đường Do Thái ở Thessaloniki suốt ba ngày Sa-bát, lập nên cộng đoàn mà ngài gửi những bức thư Tân Ước đầu tiên.",
                "sacred_relic_en": "The Roman Crypt of Saint Demetrius and the Ancient Vlatadon Monastery overlook.",
                "sacred_relic_vi": "Hầm mộ La Mã của Thánh Demetrius và Tu viện Cổ Vlatadon.",
                "scripture_reading": "1 Thessalonians 5:16-18",
                "suggested_prayer_en": "Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you. Amen.",
                "suggested_prayer_vi": "Xin cho chúng con luôn vui mừng, cầu nguyện không ngừng và tạ ơn Chúa trong mọi hoàn cảnh theo gương giáo đoàn Thêxalônica. Amen."
            },
            {
                "waypoint_id": "athens_areopagus_mars_hill",
                "name_en": "The Areopagus / Mars Hill (Athens)",
                "name_vi": "Đồi Areopagus (Đồi Mars, Athens)",
                "latitude": 37.9722,
                "longitude": 23.7236,
                "order": 3,
                "historical_summary_en": "Beneath the Parthenon, Saint Paul delivered his monumental address to the Athenian philosophers regarding the 'Unknown God' (*Acts 17:22-31*), converting Dionysius the Areopagite.",
                "historical_summary_vi": "Dưới chân đền Parthenon, Thánh Phaolô đã đọc bài diễn từ bất hủ trước các triết gia Hy Lạp về 'Vị Thần Vô Danh' (*Công vụ 17:22-31*), hoán cải Dionysius quan tòa đồi Areopagus.",
                "sacred_relic_en": "The Bronze Plaque of the Pauline Sermon at the Rock of the Areopagus.",
                "sacred_relic_vi": "Bia đồng khắc bài giảng của Thánh Phaolô trên phiến đá đồi Areopagus.",
                "scripture_reading": "Acts 17:27-28",
                "suggested_prayer_en": "O God, in whom we live and move and have our being, enlighten the minds of thinkers and leaders to discover your Truth. Amen.",
                "suggested_prayer_vi": "Lạy Thiên Chúa, Đấng mà nơi Người chúng con sinh sống, hoạt động và hiện hữu, xin soi sáng các nhà trí thức nhận biết Chân Lý Chúa. Amen."
            },
            {
                "waypoint_id": "ancient_corinth_bema",
                "name_en": "The Bema of Ancient Corinth",
                "name_vi": "Tòa Xử Án Bema Cổ Kính tại Corinth",
                "latitude": 37.9056,
                "longitude": 22.8794,
                "order": 4,
                "historical_summary_en": "Paul lived in Corinth for eighteen months as a tentmaker with Aquila and Priscilla, standing trial before Proconsul Gallio at the public *Bema* judgment seat.",
                "historical_summary_vi": "Thánh Phaolô sống tại Corinth 18 tháng làm nghề dệt lều cùng Aquila và Priscilla, từng ra hầu tòa trước Tổng trấn Gallio tại bục phán xét Bema.",
                "sacred_relic_en": "The Roman Agora Bema and the Church of Saint Paul the Apostle.",
                "sacred_relic_vi": "Tòa phán xét Bema thời La Mã và Nhà thờ Thánh Phaolô Tông Đồ Corinth.",
                "scripture_reading": "1 Corinthians 13:4-8",
                "suggested_prayer_en": "Lord, pour into our hearts the greatest of all gifts: the supernatural charity that never fails. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, xin đổ tràn vào lòng chúng con ân huệ cao trọng nhất là đức mến trọn hảo không bao giờ suy tàn. Amen."
            },
            {
                "waypoint_id": "ephesus_theatre_and_cave_of_paul",
                "name_en": "The Great Theatre and Cave of Saint Paul (Ephesus)",
                "name_vi": "Nhà Hát Lớn và Hang Đá Thánh Phaolô tại Ephesus",
                "latitude": 37.9411,
                "longitude": 27.3417,
                "order": 5,
                "historical_summary_en": "Paul ministered in Ephesus for three years, teaching daily in the Hall of Tyrannus and provoking the riot of the silversmiths in the Great 25,000-seat Theatre.",
                "historical_summary_vi": "Thánh Phaolô giảng dạy tại Ephesus suốt 3 năm tại giảng đường Tyrannus và làm bùng nổ cuộc biểu tình của các thợ bạc trong Nhà Hát 25.000 chỗ ngồi.",
                "sacred_relic_en": "The 6th-century Cave Frescoes of Saint Paul and Saint Thecla at Mount Bülbül.",
                "sacred_relic_vi": "Bích họa thế kỷ thứ 6 trong Hang Thánh Phaolô và Thánh Nữ Thecla trên núi Bülbül.",
                "scripture_reading": "Ephesians 6:14-17",
                "suggested_prayer_en": "Clothe us with the breastplate of righteousness and the shield of faith, that we may stand victorious in spiritual battle. Amen.",
                "scripture_reading": "Ephesians 6:14-17",
                "suggested_prayer_vi": "Xin mặc cho chúng con áo giáp công chính và khiên thuẫn đức tin để chiến thắng trong mọi cơn giao chiến thiêng liêng. Amen."
            },
            {
                "waypoint_id": "rome_tre_fontane_and_tomb",
                "name_en": "Abbey of the Three Fountains and Papal Basilica of Saint Paul Outside the Walls (Rome)",
                "name_vi": "Đan Viện Ba Suối Nước và Đại Vương Cung Thánh Đường Thánh Phaolô Ngoại Thành (Roma)",
                "latitude": 41.8344,
                "longitude": 12.4828,
                "order": 6,
                "historical_summary_en": "The site of Paul's martyrdom along the Via Laurentina, where his decapitated head rebounded three times causing three miraculous springs to bubble forth (*Tre Fontane*), and his resting place on the Via Ostiense.",
                "historical_summary_vi": "Nơi Thánh Phaolô chịu trảm quyết bên đường Via Laurentina, nơi đầu ngài nảy lên ba lần làm tuôn trào ba dòng suối phép lạ (*Tre Fontane*), và lăng mộ ngài bên đường Via Ostiense.",
                "sacred_relic_en": "The Decapitation Column of Saint Paul and the Apostolic Sarcophagus beneath the Papal Altar.",
                "sacred_relic_vi": "Cột đá trảm quyết Thánh Phaolô và Quan tài Hài cốt Tông Đồ dưới Bàn thờ Giáo hoàng.",
                "scripture_reading": "2 Timothy 4:7-8",
                "suggested_prayer_en": "O Great Apostle Saint Paul, you gave your life for Christ in Rome; obtain for us the grace to fight the good fight and finish the race in eternal glory. Amen.",
                "suggested_prayer_vi": "Lạy Thánh Phaolô Tông Đồ vinh hiển, ngài đã đổ máu vì Chúa Kitô tại Roma; xin cầu cho chúng con chiến đấu dũng cảm và chạy hết chặng đường đức tin để nhận triều thiên vinh hiển. Amen."
            }
        ]
    },
    {
        "route_id": "saint_olav_way",
        "title_en": "Saint Olav's Way: The Gudbrandsdalsleden to Trondheim",
        "title_vi": "Con Đường Thánh Olav: Tuyến Gudbrandsdalsleden Đến Nidaros",
        "region": "Norway (Eastern Valleys, Dovrefjell Plateau, Trøndelag)",
        "duration_days": 32,
        "distance_km": 643.0,
        "difficulty": "challenging",
        "overview_en": "Saint Olav's Way (Gudbrandsdalsleden) is the historic medieval pilgrimage route of Scandinavia, leading from the ruins of medieval Oslo through the agricultural valleys of Gudbrandsdalen, across the wild tundra plateau of Dovrefjell (rising to 1,300 meters), to Nidaros Cathedral in Trondheim—the northernmost medieval cathedral in the world enshrining the royal martyr Saint Olav Haraldsson (995–1030).",
        "overview_vi": "Con Đường Thánh Olav (Gudbrandsdalsleden) là tuyến hành hương Trung Cổ vĩ đại của vùng Scandinavia, dẫn từ phế tích Oslo cổ qua các thung lũng Gudbrandsdalen, vượt cao nguyên lãnh nguyên Dovrefjell (cao 1.300 mét) đến Nhà Thờ Chính Tòa Nidaros tại Trondheim—ngôi thánh đường Trung Cổ cực bắc thế giới lưu giữ lăng mộ Vua Thánh Tử Đạo Olav (995–1030).",
        "spiritual_theme_en": "Endurance through the Arctic wilderness: Christ conquering the northern lands and transforming warrior pride into sacrificial love.",
        "spiritual_theme_vi": "Sức kiên cường giữa thiên nhiên Bắc Cực hoang dã: Chúa Kitô biến đổi lòng kiêu hãnh của các chiến binh Viking thành tình yêu hy sinh thập giá.",
        "waypoints": [
            {
                "waypoint_id": "oslo_medieval_ruins_saint_hallvard",
                "name_en": "Old Saint Mary's and Ruins of Saint Hallvard Cathedral (Oslo)",
                "name_vi": "Nhà Thờ Đức Mẹ Cổ và Phế Tích Nhà Thờ Chính Tòa Thánh Hallvard (Oslo)",
                "latitude": 59.9056,
                "longitude": 10.7681,
                "order": 1,
                "historical_summary_en": "Pilgrims gather at the medieval stone church of Gamle Aker and the ruins of Saint Hallvard's Cathedral to receive the pilgrim blessing before heading north.",
                "historical_summary_vi": "Khách hành hương tập hợp tại nhà thờ đá Gamle Aker và phế tích Nhà thờ Chính tòa Thánh Hallvard để nhận phép lành lên đường.",
                "sacred_relic_en": "The Medieval Pilgrim Milestone of Oslo and Relics of Saint Hallvard, Patron of Oslo.",
                "sacred_relic_vi": "Cột mốc hành hương Trung Cổ Oslo và Thánh tích Thánh Hallvard, Quan Thầy thành phố Oslo.",
                "scripture_reading": "Hebrews 11:13-16",
                "suggested_prayer_en": "Lord God, guide our pilgrimage through the northern wilderness; be our light in darkness and our shelter in the storm. Amen.",
                "suggested_prayer_vi": "Lạy Chúa, xin dẫn lối cho chúng con qua vùng hoang vu phương bắc; làm ngọn đèn soi trong đêm tối và là nơi trú ẩn cho chúng con giữa bão táp. Amen."
            },
            {
                "waypoint_id": "hamar_cathedral_ruins",
                "name_en": "Hamar Cathedral Ruins (Domkirkeodden)",
                "name_vi": "Phế Tích Nhà Thờ Chính Tòa Hamar (Domkirkeodden)",
                "latitude": 60.7928,
                "longitude": 11.0397,
                "order": 2,
                "historical_summary_en": "Perched on the shores of Lake Mjøsa, the dramatic 12th-century stone arches protected within a glass cathedral enclosure stand as a monument of medieval Norwegian faith.",
                "historical_summary_vi": "Tọa lạc bên bờ hồ Mjøsa, những vòm đá thế kỷ 12 được bảo vệ trong lồng kính là đài tưởng niệm đức tin Trung Cổ của Na Uy.",
                "sacred_relic_en": "The 12th-Century Bishop's High Altar Ruins and Lake Mjøsa Sanctuary Grounds.",
                "sacred_relic_vi": "Phế tích bàn thờ chính Giám mục thế kỷ 12 bên hồ Mjøsa.",
                "scripture_reading": "Psalm 46:1-3",
                "suggested_prayer_en": "Though the mountains shake and the waters roar, God is our refuge and strength; we shall not fear. Amen.",
                "suggested_prayer_vi": "Dẫu núi non lay chuyển và sóng gầm dâng cao, Chúa vẫn là nơi trú ẩn vững bền; chúng con không hề sợ hãi. Amen."
            },
            {
                "waypoint_id": "dovrefjell_fokstugu_hermitage",
                "name_en": "Dovrefjell Plateau Hermitage of Saint Olav (Fokstugu)",
                "name_vi": "Ẩn Viện Thánh Olav Trên Cao Nguyên Dovrefjell (Fokstugu)",
                "latitude": 62.1128,
                "longitude": 9.2889,
                "order": 3,
                "historical_summary_en": "The highest and most demanding section of the pilgrimage, crossing the arctic tundra at 1,000 meters altitude where the Fokstugu mountain chapel has welcomed weary travelers since 1120 AD.",
                "historical_summary_vi": "Chặng đường cao nhất và khắc nghiệt nhất, vượt qua lãnh nguyên Bắc Cực ở độ cao 1.000 mét nơi nhà nguyện Fokstugu đón khách từ năm 1120.",
                "sacred_relic_en": "The Mountain Chapel of Saint Olav and the King's Road Pilgrim Stone.",
                "sacred_relic_vi": "Nguyện đường Thánh Olav trên núi và Phiến đá hành hương Con Đường Vua.",
                "scripture_reading": "Isaiah 40:3-5",
                "suggested_prayer_en": "In the vast silence of these frozen mountains, make straight the way of the Lord in our hearts. Amen.",
                "suggested_prayer_vi": "Giữa sự thinh lặng bao la của núi non tuyết phủ, xin Chúa uốn thẳng con đường trong tâm hồn chúng con. Amen."
            },
            {
                "waypoint_id": "nidaros_cathedral_tomb_saint_olav",
                "name_en": "Nidaros Cathedral (Tomb of Saint Olav, Trondheim)",
                "name_vi": "Đại Vương Cung Thánh Đường Nidaros (Lăng Mộ Vua Thánh Olav, Trondheim)",
                "latitude": 63.4269,
                "longitude": 10.3969,
                "order": 4,
                "historical_summary_en": "The Gothic crown of Scandinavia, built over the burial well of Saint Olav Haraldsson who died at the Battle of Stiklestad in 1030 bringing Christianity to Norway.",
                "historical_summary_vi": "Viên ngọc Gothic của bán đảo Scandinavia, xây dựng ngay trên giếng chôn cất Vua Thánh Olav—người tử trận tại Stiklestad năm 1030 để gieo mầm đức tin Công giáo tại Na Uy.",
                "sacred_relic_en": "The High Altar Crypt of Saint Olav and the Healing Well of Nidaros.",
                "sacred_relic_vi": "Hầm mộ Bàn thờ chính Vua Thánh Olav và Giếng Nước Chữa Lành Nidaros.",
                "scripture_reading": "Revelation 21:3-4",
                "suggested_prayer_en": "Saint Olav, royal martyr of the North, pray for Christian unity and steadfast fidelity across all northern lands. Amen.",
                "suggested_prayer_vi": "Lạy Vua Thánh Olav, Đấng Tử Đạo Phương Bắc, xin cầu nguyện cho sự hiệp nhất Kitô giáo và lòng trung kiên bền vững trên khắp các dân tộc. Amen."
            }
        ]
    },
    {
        "route_id": "way_of_st_cuthbert",
        "title_en": "The Way of Saint Cuthbert & Holy Island",
        "title_vi": "Con Đường Thánh Cuthbert và Đảo Thánh Lindisfarne",
        "region": "Scottish Borders and Northumberland, England",
        "duration_days": 6,
        "distance_km": 100.0,
        "difficulty": "moderate",
        "overview_en": "The Way of Saint Cuthbert links the sacred Celtic monastic sites of the Anglo-Scottish border, beginning at the ruins of Melrose Abbey in the Scottish Borders where Saint Cuthbert entered religious life in 651 AD, crossing the Cheviot hills and tidal sands of the Pilgrim's Way to Holy Island (Lindisfarne), and extending to his final resting place inside the majestic Romanesque Cathedral of Durham.",
        "overview_vi": "Con Đường Thánh Cuthbert kết nối các tu viện Celtic thánh thiện vùng biên giới Scotland và Anh, khởi đầu từ tu viện Melrose nơi ngài tu trì năm 651, băng qua rặng đồi Cheviot và bãi cát thủy triều Con Đường Hành Hương ra Đảo Thánh Lindisfarne, hướng về lăng mộ ngài trong Đại Thánh Đường Romanesque Durham.",
        "spiritual_theme_en": "Celtic monastic solitude and rhythmic contemplation: living attuned to creation, tidal rhythms, and burning apostolic charity.",
        "spiritual_theme_vi": "Sự chiêm niệm đan tu Celtic và hòa nhịp cùng thiên nhiên: sống hòa hợp với tạo thành, nhịp triều lên xuống và lòng mến Chúa tha thiết.",
        "waypoints": [
            {
                "waypoint_id": "melrose_abbey_scotland",
                "name_en": "Melrose Abbey (Scottish Borders)",
                "name_vi": "Tu Viện Cổ Melrose (Biên Giới Scotland)",
                "latitude": 55.5986,
                "longitude": -2.7181,
                "order": 1,
                "historical_summary_en": "Founded in 650 AD as Old Melrose where young Cuthbert was inspired by a vision of Saint Aidan's soul ascending to heaven, this abbey became one of Scotland's greatest Cistercian monasteries.",
                "historical_summary_vi": "Thành lập năm 650 nơi Cuthbert thời trẻ nhìn thấy thị kiến linh hồn Thánh Aidan bay lên trời, tu viện trở thành một trong những đan viện Xitô vĩ đại nhất Scotland.",
                "sacred_relic_en": "The Heart of King Robert the Bruce and 12th-century Abbey Ruins.",
                "sacred_relic_vi": "Trái tim Vua Robert the Bruce và Phế tích Tu viện thế kỷ 12.",
                "scripture_reading": "Matthew 11:28-30",
                "suggested_prayer_en": "Lord Jesus, gentle and humble of heart, take away our weariness and teach us to rest in your peaceful presence. Amen.",
                "suggested_prayer_vi": "Lạy Chúa Giêsu khiêm nhường và hiền hậu, xin cất đi gánh nặng của chúng con và dạy chúng con được nghỉ yên trong bình an của Chúa. Amen."
            },
            {
                "waypoint_id": "lindisfarne_holy_island_priory",
                "name_en": "Lindisfarne Priory and Holy Island",
                "name_vi": "Tu Viện Lindisfarne và Đảo Thánh (Holy Island)",
                "latitude": 55.6694,
                "longitude": -1.8014,
                "order": 2,
                "historical_summary_en": "The spiritual cradle of Christianity in northern England founded by Saint Aidan in 635 AD; Cuthbert governed as bishop here and retreated to Inner Farne Island for solitary prayer.",
                "historical_summary_vi": "Cái nôi đức tin của miền bắc nước Anh do Thánh Aidan lập năm 635; Thánh Cuthbert từng làm giám mục tại đây và ẩn tu trên đảo Inner Farne.",
                "sacred_relic_en": "The Priory Ruins of Saint Aidan and the Ancient Pilgrim Tidal Crossing.",
                "sacred_relic_vi": "Phế tích tu viện Thánh Aidan và Con đường thủy triều cổ dẫn sang Đảo Thánh.",
                "scripture_reading": "Psalm 95:4-7",
                "suggested_prayer_en": "O God of the tides and sea, as the waters wash over the sands of Lindisfarne, cleanse our hearts from all worldly defilement. Amen.",
                "suggested_prayer_vi": "Lạy Thiên Chúa của đại dương và sóng triều, khi làn nước tràn qua bãi cát Lindisfarne, xin thanh tẩy tâm hồn chúng con khỏi mọi vết nhơ thế trần. Amen."
            },
            {
                "waypoint_id": "durham_cathedral_tomb_saint_cuthbert",
                "name_en": "Durham Cathedral (Shrine of Saint Cuthbert and the Venerable Bede)",
                "name_vi": "Đại Thánh Đường Durham (Lăng Mộ Thánh Cuthbert và Thánh Bêđa Khả Kính)",
                "latitude": 54.7736,
                "longitude": -1.5764,
                "order": 3,
                "historical_summary_en": "Constructed in 1093 on a dramatic rocky bluff above the River Wear, Durham Cathedral is a peerless masterpiece of Norman Romanesque architecture sheltering the incorrupt body of Saint Cuthbert and the tomb of the Venerable Bede.",
                "historical_summary_vi": "Xây dựng năm 1093 trên vách đá hùng vĩ nhìn xuống sông Wear, Đại Thánh Đường Durham là kiệt tác kiến trúc Norman Romanesque bảo tồn thi hài nguyên vẹn của Thánh Cuthbert và mộ Thánh Bêđa Khả Kính.",
                "sacred_relic_en": "The Feretory Tomb of Saint Cuthbert and the Galilee Chapel Tomb of Saint Bede the Venerable.",
                "sacred_relic_vi": "Lăng mộ Thánh Cuthbert và Mộ Thánh Bêđa Khả Kính trong Nguyện đường Galilee.",
                "scripture_reading": "2 Thessalonians 2:15-17",
                "suggested_prayer_en": "Almighty God, who made Saint Cuthbert a gentle shepherd and pastor of souls, grant that we may follow his example of holy contemplation and loving service. Amen.",
                "suggested_prayer_vi": "Lạy Thiên Chúa Toàn Năng, Đấng đã biến đổi Thánh Cuthbert thành vị mục tử nhân lành chăm sóc các linh hồn, xin cho chúng con biết noi gương ngài sống đời chiêm niệm và phục vụ yêu thương. Amen."
            }
        ]
    }
]

def main():
    target_dir = "Anno/Resources/PilgrimageRoutes"
    os.makedirs(target_dir, exist_ok=True)
    
    for item in BATCH_9 + BATCH_10:
        filename = f"{item['route_id']}.json"
        path = os.path.join(target_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(item, f, ensure_ascii=False, indent=2)
        print(f"Generated {filename}")

if __name__ == "__main__":
    main()
