import json
with open('socal_vietnamese_catholic_pilgrimage_la_vang.json', 'r', encoding='utf-8') as f:
    d=json.load(f)

new_ways = [
    {
      "waypoint_id": "st_columban_church_garden_grove",
      "name_en": "St. Columban Church — Consecration Site of Bishop Thomas Thanh Thai Nguyen (Garden Grove, CA)",
      "name_vi": "Nhà Thờ Thánh Columban — Địa Điểm Tấn Phong Đức Giám Mục Thomas Thái Thành Nguyễn (Garden Grove, CA)",
      "latitude": 33.7706,
      "longitude": -117.9953,
      "order": 4,
      "historical_summary_en": "St. Columban Church in Garden Grove stands as one of the most significant Catholic sites for Vietnamese Americans — it was here, on December 19, 2017, that Bishop Thomas Thanh Thai Nguyen was consecrated as auxiliary bishop of Orange, becoming the second Vietnamese-American bishop in U.S. history. The ceremony was celebrated in four languages — English, Spanish, Vietnamese, and Korean — before an estimated 1,600 faithful, including clergy from Vietnam's St. Joseph Seminary and interfaith leaders from across the world. Bishop Nguyen himself had fled Nha Trang by boat in 1979, survived fifteen days at sea, landed in the Philippines, and immigrated to the United States in 1980; his consecration at St. Columban is therefore not merely an ecclesiastical event but a personal miracle of survival, a testament that the refugee journey from persecution can lead to the shepherding of a new Church. For a mother-in-law who loves this church, it is a living encounter: she sees her own story — the boat, the fear, the prayer — reflected in the bishop who now carries her community to Rome. The church remains a major Vietnamese parish, a place where older immigrants gather for Vietnamese-language Mass, where the 117 martyrs of Vietnam are remembered not as distant history but as family.",
      "historical_summary_vi": "Nhà Thờ Thánh Columban ở Garden Grove đứng là một trong những địa điểm Công Giáo quan trọng nhất cho người Việt Mỹ — chính tại đây, ngày 19 tháng 12 năm 2017, Đức Giám Mục Thomas Thái Thành Nguyễn đã được tấn phong làm giám mục phụ tá của Quận Orange, trở thành giám mục Mỹ gốc Việt thứ hai trong lịch sử Hoa Kỳ. Nghi lễ được cử hành bằng bốn thứ tiếng — Anh, Tây Ban Nha, Việt và Hàn Quốc — trước khoảng 1.600 tín hữu, bao gồm các linh mục từ Chủng Viện Thánh Giuse Việt Nam và các nhà lãnh đạo liên tôn từ khắp thế giới. Bản thân Đức Giám Mục Nguyễn đã chạy trốn Nha Trang bằng thuyền năm 1979, sống sót qua mười lăm ngày trên biển, đổ bộ tại Philippines và nhập cư Hoa Kỳ năm 1980; việc tấn phong của ngài tại Thánh Columban do đó không chỉ là một sự kiện giáo hội mà là một phép lạ cá nhân về sự sống sót, chứng tỏ rằng hành trình tị nạn từ bách hại có thể dẫn đến sự chăn dắt của một Giáo Hội mới. Đối với một mẹ vợ yêu mến nhà thờ này, đó là một cuộc gặp gỡ sống động: bà nhìn thấy câu chuyện của chính mình — chiếc thuyền, nỗi sợ hãi, lời cầu nguyện — được phản chiếu trong vị giám mục giờ đây mang cộng đồng của bà đến Rôma. Nhà thờ vẫn là một giáo xứ Việt Nam lớn, nơi người lớn tuổi tụ họp cho Thánh Lễ tiếng Việt, nơi 117 vị tử đạo Việt Nam được nhớ đến không phải như lịch sử xa xôi mà như gia đình.",
      "sacred_relic_en": "The consecration site of Bishop Thomas Thanh Thai Nguyen — the altar and sanctuary where he received the episcopal mitre; relics of the 117 martyrs and of the saintly Vietnamese faithful preserved by the parish; the liturgical vestments and objects used during the four-language consecration ceremony.",
      "sacred_relic_vi": "Địa điểm tấn phong của Đức Giám Mục Thomas Thái Thành Nguyễn — bàn thờ và nhà nguyện nơi ngài nhận mũ giám mục; thánh tích của 117 vị tử đạo và các vị thánh Việt Nam được giáo xứ bảo tồn; áo lễ và đồ vật phụng vụ được sử dụng trong nghi lễ tấn phong bốn thứ tiếng.",
      "scripture_reading": "Matthew 9:36-38",
      "suggested_prayer_en": "Bishop of the Boat, Shepherd of Garden Grove, who turned fifteen days of storm into a crown of service: as I stand where you were consecrated, let me feel not a visitor's awe but a family member's welcome. Make this church a true home for every Vietnamese grandmother who came by boat, for every mother who prayed in the dark, and for every child born here who now carries the name of Quảng Trị in their heart. Bless my mother-in-law, and bless every elder who has made St. Columban their own sanctuary. Amen.",
      "suggested_prayer_vi": "Giám Mục Của Chiếc Thuyền, Mục Tử Của Garden Grove, Đấng đã biến mười lăm ngày bão táp thành vương miện phục vụ: khi con đứng nơi ngài được tấn phong, xin cho con cảm nhận không phải là sự kinh ngạc của khách viếng mà là sự đón nhận của một thành viên gia đình. Xin biến nhà thờ này thành một ngôi nhà thực sự cho mọi bà cụ Việt Nam đã đến bằng thuyền, cho mọi người mẹ đã cầu nguyện trong đêm tối, và cho mọi đứa trẻ sinh ra nơi đây giờ mang tên Quảng Trị trong trái tim. Xin chúc lành cho mẹ vợ con, và chúc lành cho mọi người lớn tuổi đã biến Thánh Columban thành nơi trú ẩn của chính mình. Amen."
    },
    {
      "waypoint_id": "st_barbara_parish_westminster",
      "name_en": "St. Barbara Catholic Parish — Vietnamese Congregation Heart (Westminster, CA)",
      "name_vi": "Giáo Xứ Công Giáo Thánh Barbara — Trái Tim Cộng Đồng Việt Nam (Westminster, CA)",
      "latitude": 33.7500,
      "longitude": -117.9650,
      "order": 5,
      "historical_summary_en": "St. Barbara Parish in Westminster is one of the largest and most vibrant Vietnamese Catholic congregations in the Diocese of Orange — a church where first-generation immigrants, their American-born children, and the elderly gather for Vietnamese-language Mass, catechism, and Marian devotion. For a mother-in-law who has made this church her spiritual home, it is not merely a building but the living church of La Vang in exile: the same prayers, the same áo dài at Mass, the same remembrance of the 117 martyrs, all expressed in the language of her childhood. The parish serves as the practical bridge between the Christ Cathedral shrine (10 miles away) and the daily life of Vietnamese Catholics in Orange County — a place where the pilgrimage begins before the bus ever reaches Garden Grove.",
      "historical_summary_vi": "Giáo Xứ Thánh Barbara ở Westminster là một trong những cộng đồng Công Giáo Việt Nam lớn nhất và sống động nhất tại Quận Orange — một nhà thờ nơi những người nhập cư thế hệ đầu, con cái sinh ra tại Mỹ, và người cao niên tụ họp cho Thánh Lễ tiếng Việt, giáo lý và lòng sùng kính Mari. Đối với một mẹ vợ đã biến nhà thờ này thành nơi trú ẩn tinh thần của mình, đó không chỉ là một công trình mà là Giáo Hội sống của La Vang trong lưu đày: những lời cầu nguyện giống nhau, cùng áo dài trong Thánh Lễ, cùng ký ức về 117 vị tử đạo, tất cả được diễn tả bằng ngôn ngữ thời thơ ấu. Giáo xứ phục vụ như cầu nối thực tế giữa đền thờ Christ Cathedral (cách 10 dặm) và đời sống hàng ngày của người Công Giáo Việt Nam tại Quận Orange — một nơi mà cuộc hành hương bắt đầu trước khi chiếc xe buýt bao giờ đến Garden Grove.",
      "sacred_relic_en": "The Vietnamese-language liturgical traditions of St. Barbara Parish — the altar, the statue of Our Lady of La Vang often present, the books of Vietnamese prayer, and the community's collective memory of the 117 martyrs and the 1798 apparition.",
      "sacred_relic_vi": "Các truyền thống phụng vụ tiếng Việt của Giáo Xứ Thánh Barbara — bàn thờ, tượng Đức Mẹ La Vang thường hiện diện, sách cầu nguyện tiếng Việt, và ký ức tập thể của cộng đồng về 117 vị tử đạo và cuộc hiện ra năm 1798.",
      "scripture_reading": "Hebrews 10:24-25",
      "suggested_prayer_en": "God of St. Columban and St. Barbara, who made these churches a home for a mother-in-law, a grandmother, a refugee, and a child born in exile: let every Vietnamese Mass here be a bridge across the ocean, every prayer here be a voice from Quảng Trị, and every heart here be a living shrine. Bless her, bless her family, and bless the church she has made her own — because in her fidelity, the martyrs of Vietnam live again in California. Amen.",
      "suggested_prayer_vi": "Lạy Thiên Chúa của Thánh Columban và Thánh Barbara, Đấng đã biến các nhà thờ này thành ngôi nhà cho một mẹ vợ, một bà cụ, một người tị nạn, và một đứa trẻ sinh ra trong lưu đày: xin cho mọi Thánh Lễ tiếng Việt tại đây trở thành một cầu nối qua đại dương, mọi lời cầu nguyện ở đây trở thành tiếng nói từ Quảng Trị, và mọi trái tim ở đây trở thành một đền thờ sống. Xin chúc lành cho bà, cho gia đình bà, và cho nhà thờ mà bà đã biến thành của chính mình — vì trong sự trung kiên của bà, các vị tử đạo Việt Nam sống lại tại California. Amen."
    }
  ]
}
d['waypoints'].extend(new_ways)
for i, w in enumerate(d['waypoints'], start=1):
    w['order'] = i
with open('socal_vietnamese_catholic_pilgrimage_la_vang.json', 'w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
print('Added 2 waypoints. Total:', len(d['waypoints']))
